- app/src/main/java/com/beemdevelopment/aegis/AegisApplication.java
- app/src/main/java/com/beemdevelopment/aegis/Preferences.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
This adds an option to automatically lock the app when:
* The back button is pressed
* The device is locked
It's the first step towards implementing #7
> Add an option to automatically lock the app

- app/src/main/res/layout/activity_edit_entry.xml
It is quite common to select images with white background, so they nicely fit the design of the app. Images with white background are hard to crop because the white overlay is invisible on a white image. This PR "moves" the problem - now a background of `#ddd` is hard to crop. I am pretty sure that a white background is more common, so this should affect less users.
> Darkened Krop color

- app/src/main/java/com/beemdevelopment/aegis/crypto/CryptoUtils.java
- app/src/test/java/com/beemdevelopment/aegis/SCryptTest.java
Funny story. Instead of obtaining the actual bytes from the ByteBuffer in the password encode function, we obtained the entire buffer. This caused some trailing null bytes to be added to the encoded password. Luckily (and strangely), PBKDF2 produces collisions for inputs with trailing null bytes and thus scrypt does this as well. As such, this bug doesn't affect us right now, but it would if we were to use that encode function for other purposes in the future.
This also adds a test that checks for the expected collision behavior of scrypt.
> Fix a bug where the password encode function added trailing null bytes

- app/src/main/java/com/beemdevelopment/aegis/AegisApplication.java
- app/src/main/java/com/beemdevelopment/aegis/ui/AegisActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
This improves the way the auto-lock functionality is implemented. Instead of clearing the task stack and essentially relaunching the app, ~have ``MainActivity`` listen for calls to ``DatabaseManager.lock()``~ have all Activities listen for calls to ``AegisApplication.lock()``, so that the app can be properly locked from code outside of ``MainActivity``. 
Fixes #78.
> Fix a bug where Aegis would forcibly pop up after unlocking the device

- app/src/main/java/com/beemdevelopment/aegis/crypto/CryptoUtils.java
- app/src/main/java/com/beemdevelopment/aegis/db/slots/PasswordSlot.java
- app/src/main/java/com/beemdevelopment/aegis/db/slots/Slot.java
- app/src/main/java/com/beemdevelopment/aegis/db/slots/SlotList.java
- app/src/main/java/com/beemdevelopment/aegis/ui/AuthActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/tasks/SlotListTask.java
- app/src/main/res/values/strings.xml
- app/src/test/java/com/beemdevelopment/aegis/SCryptTest.java
Commit afb9e597110014117722fc8353333b18d3492007 fixed a bug where the password encode function would add null bytes to the end of the output. Luckily (I thought), PBKDF2 produces collisions for inputs with trailing null bytes and thus scrypt does this as well, so we could safely change that function to remove the null bytes without any impact. Unfortunately, that doesn't hold up if the password is over 64 bytes in size. So after that change, the KDF started producing different keys than before for such passwords and thus some users could no longer unlock their vault.
This patch addresses the issue by using the old password encode function for passwords over 64 bytes and repairing the affected password slot.
> Use the old encode method for passwords over 64 bytes and repair the slot

- app/src/main/java/com/beemdevelopment/aegis/ui/AegisActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
This patch ensures that AuthActivity is always launched on lock, even from ScreenOffReceiver events, but only if MainActivity is resumed.
Fixes #96.
> Always launch AuthActivity on lock if MainActivity is resumed

- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
This fixes a bug where AuthActivity would be shown after finishing the intro.
> Don't ignore the result of IntroActivity when the vault is locked

- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/SelectEntriesActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/models/ImportEntry.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/ImportEntriesAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/ImportEntryHolder.java
- app/src/main/res/values-fr/strings.xml
This horrid patch changes the vault import logic to pass an ImportEntry list to SelectEntriesActivity, instead of a DatabaseEntry list. Previously, a crash would occur when importing a vault with lots of icons, because the maximum Parcel size was exceeded.
Storing icons in the vault file was a bad idea.
> Limit the amount of entry info passed to SelectEntriesActivitiy

- app/src/main/java/com/beemdevelopment/aegis/ViewMode.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryHolder.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
- app/src/main/res/drawable/entry_divider.xml
- app/src/main/res/layout/activity_auth.xml
- app/src/main/res/layout/activity_edit_entry.xml
- app/src/main/res/layout/activity_groups.xml
- app/src/main/res/layout/activity_intro.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/activity_scanner.xml
- app/src/main/res/layout/activity_slots.xml
- app/src/main/res/layout/card_entry.xml
- app/src/main/res/layout/card_entry_compact.xml
- app/src/main/res/layout/card_entry_small.xml
- app/src/main/res/menu/menu_edit.xml
- app/src/main/res/menu/menu_main.xml
- app/src/main/res/menu/menu_scanner.xml
- app/src/main/res/menu/menu_slots.xml
This patch makes EntryListView responsible for providing the divider between entries, instead of setting a margin on every entry like we do now. It also fixes a couple of miscellaneous issues, like use of the old package name.
> Move entry divider logic to EntryListView

- app/build.gradle
- app/src/main/java/com/beemdevelopment/aegis/Preferences.java
- app/src/main/res/xml/preferences.xml
I've lost count of how many times I've tried to record a demo video with screen security enabled.
> Disable screen security by default for debug builds

- app/build.gradle
- app/src/main/java/com/beemdevelopment/aegis/ui/EditEntryActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/glide/AegisGlideModule.java
- app/src/main/java/com/beemdevelopment/aegis/ui/glide/IconLoader.java
- app/src/main/java/com/beemdevelopment/aegis/ui/glide/UUIDKey.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryHolder.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
This patch adds a dependency to glide to handle the loading and caching of icons. In my testing it eliminated the lag previously experienced in the main activity when quickly scrolling through a large list of entries. It does add an extra 1MB to the APK size, but I think that's acceptable for the amount of complexity it handles for us. 
Addresses #125 partially.
> Use glide to load and cache icons

- app/src/main/java/com/beemdevelopment/aegis/helpers/UiRefresher.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryHolder.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
We were leaking some resources by not unregistering listeners when destroying the entry list view. The code refresh loop of the leaked view started running in a tight infinite loop, which causes a lot of lag in the main activity.
Partially addresses #125.
> Unregister any listeners when destroying EntryListView

- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryHolder.java
Codes with an uneven number of digits were displayed incorrectly. This patch fixes that.
Fixes #175.
> Correctly display codes with an uneven number of digits

- app/src/main/java/com/beemdevelopment/aegis/otp/TotpInfo.java
The conversion of the OTP period value to milliseconds may overflow for large values, causing the result to wrap around to ``Integer.MIN_VALUE``. This subsequently caused a crash when calling ``ObjectAnimator.setDuration``.
Fixes #152.
> Check for the possibility of an overflow when parsing OTP period

- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
- app/src/main/res/xml/preferences.xml
I made the "Auto lock" preference depend on the "Encryption" preference. The order is also changed and will it now be shown below the encryption preference.
If "Encryption" is disabled, the "auto lock" won't be visible.
> Change auto lock preference visibility behaviour

- app/src/main/java/com/beemdevelopment/aegis/CancelAction.java
- app/src/main/java/com/beemdevelopment/aegis/ui/AuthActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
This pull request adds a temporary (~and dirty~) fix so Aegis will close when using Androids' back button.
Fixes #182 and eventually #180 too. This definitely needs a overhaul but it's good for now.
> Add temporary backpress fix

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/assets/changelog.html
- app/src/main/java/com/beemdevelopment/aegis/ui/AboutActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/AegisActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/ChangelogDialog.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/glide/GlideLicense.java
- app/src/main/res/layout/activity_about.xml
- app/src/main/res/layout/content_about.xml
- app/src/main/res/layout/dialog_web_view.xml
- app/src/main/res/menu/menu_main.xml
- app/src/main/res/raw/glide_license.txt
- app/src/main/res/raw/notices.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- gradle/wrapper/gradle-wrapper.properties
This pull requests adds a new AboutActivity which is available from the overflow (3-dots) menu in the MainActivity. It currently looks like this but there is room for improvement.
I've also made light, dark and amoled themes for the dialogs which were needed for the "Licenses" and "Changelog" dialogs.
Closes #137
> Add AboutActivity

- app/src/main/java/com/beemdevelopment/aegis/Preferences.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
This pull requests adds an additional preference item which allows the user to include account name matches in the search results as suggested in #197.
Closes #197
> Add ability to search in account names

- app/src/main/java/com/beemdevelopment/aegis/Preferences.java
- app/src/main/res/xml/preferences.xml
This changes the default settings so that account names are shown by default
> Set pref_account_name to true by default

- app/src/main/java/com/beemdevelopment/aegis/importers/AndOtpImporter.java
- app/src/main/res/values/strings.xml
This patch adds support for the new backup file format of andOTP. andOTP has improved their security by switching from SHA-256 to PBKDF2 to derive the key for encrypted backups.
Glad to see this has been addressed now. Awesome work, @flocke!
See: andOTP/andOTP@d96b037.
Close #215.
> Add support for the new andOTP backup format

- app/src/main/java/com/beemdevelopment/aegis/Preferences.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryHolder.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
This adds an option to highlight tapped entries, so that it's easier to distinguisch between the one you're trying to enter into a website and the other ones.
Only one entry can be highlighted at a time. Perhaps it would make sense to change our tap to reveal functionality to behave the same, so that the two features are nicely in sync. I can address that in a separate PR if we decide to do so.
> Add the option to highlight entries when tapped

- app/src/main/AndroidManifest.xml
This hopefully fixes #226. I tested this on a Chromebook emulator, but it let me install the app even without this patch, so we'll have to wait and see if this fixes it when we release a new version.
> Explicitly state in AndroidManifest that a camera is not required

- app/src/main/java/com/beemdevelopment/aegis/ui/Dialogs.java
- app/src/main/java/com/beemdevelopment/aegis/ui/slides/CustomAuthenticatedSlide.java
- app/src/main/res/layout/dialog_password.xml
- app/src/main/res/layout/fragment_authenticated_slide.xml
- app/src/main/res/values/strings.xml
This checkbox disables the 'Confirm password' field since I don't think it's needed when the password is visible.
Closes #228
> Add checkbox to toggle visibility in password fields

- app/src/main/java/com/beemdevelopment/aegis/ui/tasks/ProgressDialogTask.java
- app/src/main/java/com/beemdevelopment/aegis/ui/tasks/SlotListTask.java
The import failed because `Dialog.setMessage()` happens on the wrong thread. I decided to use the progress update mechanism, as `new Handler(Looper.getMainLooper()).post(runnable)` felt more awkward than it needed to be. If you don't agree feel free to do it differently.
> Fix exception when importing an old export

- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryHolder.java
I think this makes the highlight/reveal functionality feel a bit more consistent, by not allowing multiple entries to be revealed at the same time, just like you can't have multiple highlighted entries.
Here's video of what it looks like: https://alexbakker.me/u/3a9dhplrj2.mp4.
> Make the behavior of highlighting and revealing entries consistent

- app/build.gradle
- build.gradle
We may want to merge this before releasing 1.1, so that androidx.biometeric is updated to [1.0.1](https://developer.android.com/jetpack/androidx/releases/biometric#version_101_3).
> Update gradle and dependencies

- app/src/main/assets/changelog.html
- app/src/main/java/com/beemdevelopment/aegis/ui/ChangelogDialog.java
Apparently the webview in API 29 doesn't like hex colors
> Fix changelog

- app/src/main/AndroidManifest.xml
This is a temporary workaround for #274 while we work on support for the Storage Access Framework.
> Set requestLegacyExternalStorage to true in AndroidManifest

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultManager.java
- app/src/main/res/values/strings.xml
We noticed after the v1.1 release that we need to switch our external storage access code over to use the Storage Access Framework. The export functionality was the only piece of code that still used the deprecated method and this patch addresses that.
The Storage Access Framework is a little annoying to work with, but I don't think it'll be too painful for our usecase. This switch comes with some nice benefits for users as well. Users are now able to select a custom storage location, which can be local or in the cloud.
This also removes ``requestLegacyExternalStorage`` from the manifest, as we don't need it anymore.
> Rewrite the export functionality to use the Storage Access Framework

- app/src/main/java/com/beemdevelopment/aegis/ui/Dialogs.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
- app/src/main/res/values/strings.xml
This pull request adds the ability to select multiple entries as proposed in #277.
It automatically disables the copy, edit and drag features as these are not supported when having multiple entries selected. Please test this feature with 'tap to reveal' / 'highlight' enabled and disabled.
> Add ability to select multiple entries

- app/src/main/java/com/beemdevelopment/aegis/ui/AegisActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
This pull request fixes the bug with setting locale on Android 7.0 as reported in #287. 
I also hid the 'Language'-preference on KitKat since it doesn't work on Kitkat.
> Fix setting locale on 7.0

- app/src/main/java/com/beemdevelopment/aegis/vault/VaultManager.java
Apparently not all SAF providers append a file extension based on the specified
MIME type.
> Append ".json" extension to export filenames

- app/src/main/res/values-v21/styles.xml
- app/src/main/res/values/styles.xml
As highlighted in issue #244, with different vendors the navbar is light on the dark and the amoled theme. I've fixed it for Samsung One UI 2.0 and tested it on vanilla Android on a Pixel 3, but it should work on every device and correctly fallback to default navigation bar colors on older android versions.
> Add navigation bar color to themes

- app/build.gradle
- app/src/main/java/com/beemdevelopment/aegis/crypto/CryptParameters.java
- app/src/main/java/com/beemdevelopment/aegis/encoding/Base32.java
- app/src/main/java/com/beemdevelopment/aegis/encoding/Base32Exception.java
- app/src/main/java/com/beemdevelopment/aegis/encoding/Base64.java
- app/src/main/java/com/beemdevelopment/aegis/encoding/Base64Exception.java
- app/src/main/java/com/beemdevelopment/aegis/encoding/EncodingException.java
- app/src/main/java/com/beemdevelopment/aegis/encoding/Hex.java
- app/src/main/java/com/beemdevelopment/aegis/encoding/HexException.java
- app/src/main/java/com/beemdevelopment/aegis/importers/AegisImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/AndOtpImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/AuthyImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/GoogleAuthImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/SteamImporter.java
- app/src/main/java/com/beemdevelopment/aegis/otp/GoogleAuthInfo.java
- app/src/main/java/com/beemdevelopment/aegis/otp/OtpInfo.java
- app/src/main/java/com/beemdevelopment/aegis/ui/EditEntryActivity.java
- app/src/main/java/com/beemdevelopment/aegis/vault/Vault.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultEntry.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultFile.java
- app/src/main/java/com/beemdevelopment/aegis/vault/slots/Slot.java
- app/src/test/java/com/beemdevelopment/aegis/SCryptTest.java
- app/src/test/java/com/beemdevelopment/aegis/TOTPTest.java
I kept the classes in the ``encoding`` package and turned them into wrappers for Guava. I also changed the functions in the Base32 class to take and return strings insteads if character arrays.
Fixes #259.
> Replace implementations of Base16, Base32 and Base64 with Guava

- app/src/main/java/com/beemdevelopment/aegis/importers/DatabaseImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/DatabaseImporterEntryException.java
- app/src/main/java/com/beemdevelopment/aegis/importers/GoogleAuthImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/MicrosoftAuthImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/SqlImporterHelper.java
Adds support for importing TOTP and Microsoft accounts from Microsoft Authenticator. Microsoft accounts also use TOTP, but with 8 digits instead of 6.
This implementation suffers from the same bug (#82) as Google Authenticator, but I haven't thought of a nice way to solve it yet. We should fix that before including this feature in a release, though.
Closes #186.
> Add support for importing from Microsoft Authenticator

- app/src/main/java/com/beemdevelopment/aegis/ui/AuthActivity.java
I only added it to the AuthActivity since I think it's nice to have a confirmation while setting it up.
Fixes #321
> Set confirmation not required on BiometricPrompt

- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryHolder.java
If you set an account name to an empty string, right now you see a trailing dash, e.g. `Github - `.
This change should fix this, so that the dash is only added when account name is not empty.
> Show account name only if it's set

- app/src/main/java/com/beemdevelopment/aegis/Preferences.java
- app/src/main/java/com/beemdevelopment/aegis/Theme.java
- app/src/main/java/com/beemdevelopment/aegis/ui/AegisActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesActivity.java
- app/src/main/res/values-v29/strings.xml
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
added an implementation of Android 10 (API 29) dark theme
added two new theme options:
SYSTEM: dynamically switches between light and dark theme
SYSTEM_AMOLED: dynamically switches between light and amoled theme
changed the default theme to be SYSTEM
reversed [this workaround](https://github.com/beemdevelopment/Aegis/commit/59c0ca947dfec842e7b24fcddca34538bcc709d2) for amoled themed preferences to remove duplicated code in `PreferencesActivity.java`
(I'm not sure why this workaround was needed but I just added the true dark background to the normal amoled theme)
The launch screen will always follow the system theme regardless of which theme was selected. There is no other way to do it because the color of the launch screen can only be set in XML which means no preferences can be queried. …
> automatically adapt to system theme

- app/src/main/java/com/beemdevelopment/aegis/ui/AuthActivity.java
I noticed a strange crash in the Play Console:
```
android.view.WindowManager$BadTokenException:
at android.view.ViewRootImpl.setView (ViewRootImpl.java:828)
at android.view.WindowManagerGlobal.addView (WindowManagerGlobal.jav>
at android.view.WindowManagerImpl.addView (WindowManagerImpl.java:93)
at android.widget.PopupWindow.invokePopup (PopupWindow.java:1434)
at android.widget.PopupWindow.showAsDropDown (PopupWindow.java:1284)
at android.widget.PopupWindow.showAsDropDown (PopupWindow.java:1240)
at android.widget.PopupWindow.showAsDropDown (PopupWindow.java:1219)
at com.beemdevelopment.aegis.ui.AuthActivity.lambda$showPasswordRemi>
at com.beemdevelopment.aegis.ui.-$$Lambda$AuthActivity$WWHxRKllBPcyH>
at android.os.Handler.handleCallback (Handler.java:873)
at …
```
> Show the password reminder popup after the window has been attached

- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
This pull request changes the way the timers are shown as suggested #231. The EntryAdapter now finds the most frequent period to differentiate between the listview progressbar and the entry progressbar.
Closes #231
> Use most frequent period to show progress

- app/build.gradle
- app/proguard-rules.pro
This enables some minification and optimization options to shrink the size of
our APK. A release APK would previously be 12 MB in size, but would now be 8.2
MB.
To test, check if *all* of the functionality of the app still works,
particularly parts that refer to dependencies. You'll know if ProGuard broke
something when the app crashes with a ``ClassNotFoundException`` or similar
exception. I think I've covered all of the cases where ProGuard removed too much
in the rule file.
Also, I was curious why our APK had gotten so large to begin with. I did some
digging and found that this is caused by the SQLCipher dependency. The APK
shrinks down to 2.7 MB without it! We should consider whether having support for
importing from Authenticator Plus is worth the extra 5.5 MB in size.
> Minify and optimize the APK using ProGuard

- app/src/main/java/com/beemdevelopment/aegis/ui/AegisActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/EditEntryActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultManager.java
This makes it so that EditEntryActivity directly saves entries to the vault, instead of passing them back to MainActivity through an Intent first. This prevents crashes that can occur when an entry has a large icon and the Bundle inside the Intent becomes too large.
This is the first part of a series of patches I plan on submitting, where I try to repair the damage done by my misguided obsession of only touching the global state in certain places.
> Write entries to the vault directly in EditEntryActivity

- app/src/main/java/com/beemdevelopment/aegis/ui/AboutActivity.java
- app/src/main/res/layout/content_about.xml
- app/src/main/res/values/strings.xml
Switched from the default blue to the accent color
Also fixed lint issues in About activity layout
> Change license link color so it is legible on dark

- app/src/main/java/com/beemdevelopment/aegis/Preferences.java
- app/src/main/java/com/beemdevelopment/aegis/ui/Dialogs.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/res/layout/dialog_time_sync.xml
- app/src/main/res/values/strings.xml
This'll display a warning to users who don't have automatic time synchronization enabled on their device. Aegis will try to take the user to the right settings menu if they tap "Yes". Users also have the option to silence the warning.
[<img width=300 src="https://alexbakker.me/u/jf1o8087lr.png">](https://alexbakker.me/u/jf1o8087lr.png)
> Display a warning if automatic time sync is not enabled

- app/build.gradle
- app/proguard-rules.pro
- app/src/main/java/com/beemdevelopment/aegis/otp/GoogleAuthInfo.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/ScannerActivity.java
- app/src/main/proto/google_auth.proto
- app/src/main/res/values/strings.xml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
This adds initial support for importing the new Google Authenticator QR codes shown when exporting. I'm not 100% sure if I got all of the types in the protobuf message definitions correct, but it seems to work well.
> Add initial support for importing Google Authenticator export QR codes

- app/src/main/java/com/beemdevelopment/aegis/Preferences.java
We got multiple reports from users who think the passwords reminder triggered too fast (once every 7 days). This pull request increases that period to 30 days as suggested in #402.
Do note that we also made an option to disable this reminder entirely.
Fixes #402.
> Increase password reminder period to 30 days

- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesActivity.java
This fixes an issue where the existing PreferencesFragment was discarded when restoring PreferencesActivity from instance state. This issue caused the PreferencesFragment to no longer receive activity results. Most notably, this resulted in 0 byte vault files being created when exporting the vault.
Fixes #401.
> Reuse existing PreferencesFragment when restoring from instance state

- app/build.gradle
- app/lint.xml
- app/proguard-rules.pro
- app/src/main/java/com/beemdevelopment/aegis/crypto/CryptoUtils.java
- app/src/main/res/values-zh-rCN/strings.xml
SpongyCastle is a fork of BouncyCastle. We originally used this fork to 1) have access to scrypt and 2) prevent a package name collision with the bundled BouncyCastle. We don't actually need to use the fork anymore, because the package name of the bundled BouncyCastle was changed in Android. SpongyCastle has also gotten quite outdated in recent years.
The built-in version of BouncyCastle is replaced with the one bundled with the app at runtime, so that we have a recent version even on older Android versions.
This also updates Gradle and the Gradle Android plugin, to fix a build error I was running into when I added the dependency to BouncyCastle.
Fixes #360.
> Replace SpongyCastle with BouncyCastle

- app/src/main/java/com/beemdevelopment/aegis/ui/IntroActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/slides/CustomAuthenticatedSlide.java
Also fixes another issue where previously, if a user made it to the last intro slide and then navigated back to change the security options, any changes would be ignored. Supersedes #434.
> Fix issue where VaultManager was erroneously initialized with creds in intro

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/beemdevelopment/aegis/ui/AboutActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/GroupManagerActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesActivity.java
- app/src/main/res/values/strings.xml
For the sake of consistency I added the back button to the action bar for both the "Settings" and "About" intents. "Settings" now also has a translatable string as title instead of the app title.
Does it make sense to replace the cross by an arrow in the "Manage Groups" action bar?
> Improve Action Bar consistency for Settings and About

- app/src/main/java/com/beemdevelopment/aegis/ui/EditEntryActivity.java
- app/src/main/res/menu/menu_edit.xml
- app/src/main/res/values/strings.xml
This improves the entry icon editing flow as suggested in #252:
- Add an "Edit icon" menu item
- Save the icon even if the checkmark was not clicked
- Exit icon edit mode with the back button
Close #252.
> Improve icon editing flow

- app/src/main/java/com/beemdevelopment/aegis/encoding/Base32.java
- app/src/main/java/com/beemdevelopment/aegis/importers/AndOtpImporter.java
These larger numbers of iterations cause the key derivation process to take
longer, so I also moved that task to the background. andOTP now also has a
proper "issuer" field, so we make use of that as well.
Also fixes an issue where padded base32 could not be decoded. This issue is only
present for the andOTP importer as far as I know, so that's why that change is
included here.
> Fix importing andOTP backups with more than 10000 PBKDF iterations

- app/src/main/java/com/beemdevelopment/aegis/ui/AuthActivity.java
We no longer create BiometricPrompt prematurely, but forgot to adjust the check for the password reminder.
> Fix an issue where the password reminder popup was not shown

- app/src/main/java/com/beemdevelopment/aegis/ui/IntroActivity.java
This fixes a number of issues that can happen when navigating back to previous slides, by disabling back navigation entirely. One such issue is that when navigating back from the last slide, one would always land on the password/biometrics setup slide, even if "none" was selected on the security picker slide.
> Disable wizard mode when the done slide of the intro is reached

- app/src/main/java/com/beemdevelopment/aegis/Preferences.java
- app/src/main/java/com/beemdevelopment/aegis/ui/AegisActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/AuthActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/EditEntryActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultManager.java
- app/src/main/res/drawable/ic_alert_black_24dp.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/values/strings.xml
This patch improves our backup functionality in a number of ways:
- Only backup the vault when important changes are made, not when the order of
entries is changed, for instance.
- Don't bubble up backup errors when saving the vault.
- Instead, show an error bar in the main view if the most recent backup attempt
failed.
Clicking on the error bar will take the user to the backup settings.
> Improve backup error handling and frequency

- app/src/main/java/com/beemdevelopment/aegis/ui/AegisActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/AuthActivity.java
We previously stopped/started the biometric prompt every time in
onPause/onResume, but that's apparently not necessary (and discouraged according
to the documentation). This caused issues where the prompt would get stuck on
some devices. While working on this I ran into another issue where AuthActivity
was closed and reopened for no reason after rotation of the device, compounding
the issue. This patch also fixes that.
Fixes #342.
> Let Android handle the lifecycle of BiometricPrompt

- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryHolder.java
- app/src/main/res/values-cs-rCZ/strings.xml
- app/src/main/res/values-de-rDE/strings.xml
- app/src/main/res/values-el-rGR/strings.xml
- app/src/main/res/values-es-rES/strings.xml
- app/src/main/res/values-fi-rFI/strings.xml
- app/src/main/res/values-fr-rFR/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-it-rIT/strings.xml
- app/src/main/res/values-kn-rIN/strings.xml
- app/src/main/res/values-nl-rNL/strings.xml
- app/src/main/res/values-pl-rPL/strings.xml
- app/src/main/res/values-ru-rRU/strings.xml
- app/src/main/res/values-tr/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
This pull request changes the 'Hidden' text to a repeating single character as suggested [here](https://github.com/beemdevelopment/Aegis/issues/475). We went for the black circle unicode character (●) as it looks better than asterisks since these are centered and bigger. This feature also respects the 'Code digit grouping' preference as seen in the image below.
Fixes #475.
> Change hidden text to the 'Black circle' character

- .travis.yml
- .travis/android-wait-for-launcher.sh
- app/build.gradle
- app/proguard-rules.pro
- app/src/androidTest/java/com/beemdevelopment/aegis/AegisTest.java
- app/src/androidTest/java/com/beemdevelopment/aegis/AegisTestRunner.java
This patch adds an initial set of UI tests for Aegis built using Espresso. It
covers a fair bit of the essential functionality of the app, but there are lots
more tests we could add later on.
This also reconfigures our Travis CI build manifest to run the tests on API 21,
23, 27 and 28 emulators. It was a real pain to get this to work well, but let's
hope it's stable now.
I had to downgrade ``com.google.android.material`` to 1.0.0, because 1.1.0
introduced an issue where the test would hang.
> Add initial set of UI tests

- app/src/main/java/com/beemdevelopment/aegis/importers/AegisImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/AndOtpImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/AuthenticatorPlusImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/AuthyImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/DatabaseImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/FreeOtpImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/FreeOtpPlusImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/GoogleAuthImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/GoogleAuthUriImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/MicrosoftAuthImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/SqlImporterHelper.java
- app/src/main/java/com/beemdevelopment/aegis/importers/SteamImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/TotpAuthenticatorImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/WinAuthImporter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
This patch ensures that we also copy over any files related to the SQLite
database (databases-shm, databases-wal, databases-journal) when copying it from
an app's internal storage.
Fixes #82.
> Fix the flakiness of importing from SQLite databases

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/beemdevelopment/aegis/AegisApplication.java
- app/src/main/java/com/beemdevelopment/aegis/ui/AegisActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
We don't actually need this, and I have a feeling that it may be causing some of
the inexplicable crashes we're seeing in the Play Console. For example:
apparently the app sometimes gets itself into a state where the vault is
unlocked, but the user is still shown AuthActivity (possibly due to it being
launched twice). I can't prove that "singleTask" causes this, as I can't
reproduce the issue on my device or an emulator, but it's the only odd thing we
have in our activity lifecycle handling.
Test plan:
- Go through the intro, add an entry, change some settings, etc
- See if the app shortcuts still work. Scenarios:
- The app is terminated.
- The app is locked.
- MainActivity is open.
- Some other activity is open.
- See if auto-locking still works. Scenarios:
- The app is locked.
- …
> Unset "singleTask" as the launchMode for MainActivity

- app/src/main/java/com/beemdevelopment/aegis/crypto/KeyStoreHandle.java
We're looking for android.security.KeyStoreException as the cause of
ProviderException, not java.security.KeyStoreException. Unfortunately this is a
hidden class, so all we can do is check the class name.
> Fix catching ProviderException with KeyStoreException as the cause

- app/src/main/java/com/beemdevelopment/aegis/ui/AuthActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
This is a different take on what db681273e6524cc450170e02979a9cf21264aab1 was trying to accomplish, with the additional benefit that the prompt will now no longer be shown on auto-lock.
> Improve the lifecycle handling of BiometricPrompt some more

- app/src/main/java/com/beemdevelopment/aegis/ui/views/TotpProgressBar.java
If the animator scale setting is set to 0, the progress bar refresher would run in a tight loop. This issue was introduced by 93cc945a2c9cd1cdaefc745b33a196cdeec198ac and caused the UI tests to fail.
> Fix an issue where the progress bar refresher ran in a tight loop

- app/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Fixes #520 <s>by downgrading com.google.zxing package to 3.3.3 (in 3.4.0 they dropped support of older Androids which are still widely used worldwide)</s> by adding desugaring for some features used in com.google.zxing
> Preserve backwards compatibility with Android < 7.0

- app/src/main/java/com/beemdevelopment/aegis/Preferences.java
- app/src/main/java/com/beemdevelopment/aegis/ui/AuthActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/Dialogs.java
- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
This pull request allows the user to enable a PIN keyboard to use on the lockscreen. Before it can be enabled it will check if your password consists of digits. As a fallback we decided to set the keyboard to text after 3 failed attempts, which shouldn't be needed but we just wanted to make sure we don't lock users out of their vault.
I also included a fix to dismiss the keyboard if the user triggers the bioprompt.
Closes #54
> Add ability to enable PIN keyboard

- app/src/main/res/values/strings.xml
Setup is a noun (i.e. the setup process), whereas "set up" is a verb. (i.e. to set something up). 
e.g. Once _the setup_ has been completed, you would say Aegis has _been  set up_.
> Grammar fix (setup -> set up)

- app/src/main/java/com/beemdevelopment/aegis/ui/GroupManagerActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
- app/src/main/res/drawable/ic_layers_black_24dp.xml
- app/src/main/res/layout/activity_groups.xml
- app/src/main/res/values/strings.xml
This pull requests adds an empty state view for the GroupManagerActivity found in the preferences. Also added a fix where the deleted groups didn't get saved properly.
Closes #553
> Add empty state for GroupManagerActivity

- app/src/main/java/com/beemdevelopment/aegis/ui/EditEntryActivity.java
This could happen in rare cases where writing the vault to disk failed.
> Prevent a crash caused by adding the same entry to the vault twice

- app/src/main/java/com/beemdevelopment/aegis/helpers/ContextHelper.java
- app/src/main/java/com/beemdevelopment/aegis/importers/AndOtpImporter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/AuthActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/Dialogs.java
- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/slides/SecuritySetupSlide.java
- app/src/main/java/com/beemdevelopment/aegis/ui/tasks/ProgressDialogTask.java
This patch ensures ProgressDialogs are dismissed when the ON_PAUSE event is fired.
Fixes #159.
> Prevent a crash on rotation while a ProgressDialogTask is still running

- app/src/main/java/com/beemdevelopment/aegis/ui/Dialogs.java
- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/SelectEntriesActivity.java
- app/src/main/java/com/beemdevelopment/aegis/util/UUIDMap.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultManager.java
- app/src/main/res/layout/dialog_checkbox.xml
- app/src/main/res/values/strings.xml
This pull request adds a checkbox dialog when importing a file when the vault already contains entries. When the checkbox is checked, all the existing entries will be wiped. This was suggested in #276.
Closes #276.
> Add checkbox dialog to wipe vault before import

- app/src/main/res/drawable/entry_divider.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/styles.xml
This pull request adds some minor theme improvement as discussed in #294.
Left: this pull request, right: old color
Closes #294
> Minor color improvements for dark themes

- app/build.gradle
- app/src/main/java/com/beemdevelopment/aegis/AegisApplication.java
- app/src/main/java/com/beemdevelopment/aegis/CancelAction.java
- app/src/main/java/com/beemdevelopment/aegis/Preferences.java
- app/src/main/java/com/beemdevelopment/aegis/ui/AegisActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/AuthActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
- app/src/main/res/values-ar-rSA/strings.xml
- app/src/main/res/values-cs-rCZ/strings.xml
- app/src/main/res/values-de-rDE/strings.xml
- app/src/main/res/values-el-rGR/strings.xml
- app/src/main/res/values-es-rES/strings.xml
- app/src/main/res/values-fi-rFI/strings.xml
- app/src/main/res/values-fr-rFR/strings.xml
- app/src/main/res/values-hu-rHU/strings.xml
- app/src/main/res/values-it-rIT/strings.xml
- app/src/main/res/values-kn-rIN/strings.xml
- app/src/main/res/values-nl-rNL/strings.xml
- app/src/main/res/values-pl-rPL/strings.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values-pt-rPT/strings.xml
- app/src/main/res/values-ru-rRU/strings.xml
- app/src/main/res/values-tr-rTR/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
This patch makes the auto lock option more customizable. Users can now choose a
combination of the following: Locking Aegis when
- The back button is pressed
- The app is minimized
- The device is locked
Close #541 and close #334.
> Improve auto lock and make it more customizable

- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
- app/src/main/res/values/strings.xml
This fixes an issue where the PIN keyboard was shown after a password change, regardless of whether it only contained digits or not.
> Reset the PIN keyboard option when the password is changed

- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
- app/src/main/res/values/strings.xml
This PR should satisfy #585 by showing a simple toast message if the backup was created successfully.
> Show toast message if backup was created successfully

- app/src/main/java/com/beemdevelopment/aegis/helpers/BitmapHelper.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
I'm not sure why this works, but ZXing seems to have trouble with high resolution images. For example, scanning a 4032x3024 image with a QR code in it fails, but scanning a resized version of that exact same image works.
Fixes #538.
> Resize images to a max res of 640x480 before scanning for QR codes

- app/build.gradle
- app/src/androidTest/java/com/beemdevelopment/aegis/AegisTestRunner.java
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/beemdevelopment/aegis/AegisApplication.java
- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/util/IOUtils.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultBackupManager.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultManager.java
- app/src/main/res/layout/dialog_export.xml
- app/src/main/res/values-ar-rSA/strings.xml
- app/src/main/res/values-cs-rCZ/strings.xml
- app/src/main/res/values-el-rGR/strings.xml
- app/src/main/res/values-es-rES/strings.xml
- app/src/main/res/values-fi-rFI/strings.xml
- app/src/main/res/values-fr-rFR/strings.xml
- app/src/main/res/values-hu-rHU/strings.xml
- app/src/main/res/values-it-rIT/strings.xml
- app/src/main/res/values-nl-rNL/strings.xml
- app/src/main/res/values-pl-rPL/strings.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values-pt-rPT/strings.xml
- app/src/main/res/values-ru-rRU/strings.xml
- app/src/main/res/values-tr-rTR/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/file_paths.xml
This patch improves the export functionality in the following ways:
1. Allow setting a password even if the Aegis vault is not encrypted
2. Display a scary warning when exporting an unencrypted vault
3. Support exporting to a Google Authenticator URI file
4. Option to use Android's share mechanism
Close #512, close #138, close #508.
> Improve the export functionality in numerous ways

- app/src/main/java/com/beemdevelopment/aegis/ui/Dialogs.java
"Tap to reveal" currently allows setting the display time to 3 seconds or more.
However, as a single second is actually enough to read the token, the duration of 1 and 2 seconds should be available as option for users that want to choose such short duration for improved privacy/security.
> "Tap to reveal": change min duration from 3 to 1

- app/src/main/java/com/beemdevelopment/aegis/AegisApplication.java
- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/tasks/ExportTask.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultBackupManager.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultManager.java
- app/src/main/res/values/strings.xml
This writes exports/backups to the cache directory first and then hands off to a background thread to pipe the file to SAF. I'm cheating a bit, but it's the easiest fix with our current architecture. In the future, we should skip the first step by making VaultManager itself thread-safe.
Fixes #610.
> Move the creation of exports/backups to a background thread

- app/src/main/java/com/beemdevelopment/aegis/helpers/MetricsHelper.java
- app/src/main/java/com/beemdevelopment/aegis/ui/AuthActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
This prevents the Android's autofill popup from occluding our popup
> Display the password reminder popup on top instead of the bottom

- app/src/main/AndroidManifest.xml
This is necessary to be able to see if the app a user wants to import from is installed.
See: https://developer.android.com/about/versions/11/privacy/package-visibility
Fixes #638.
> Explicitly define which packages (apps) we want to query

- app/src/main/java/com/beemdevelopment/aegis/otp/GoogleAuthInfo.java
- app/src/main/proto/google_auth.proto
I don't think Google Authenticator actually currently supports any of these
extra digit/algorithm options, but they're specified in the proto file, so we
should support them for completeness sake.
> Make the Google Authenticator Protobuf parser more complete

- app/src/main/java/com/beemdevelopment/aegis/AegisApplication.java
This ensures we're able to access other app's internal storage directories using libsu when running on Android 11 or newer.
> Run libsu commands inside the global mount namespace

- app/src/main/java/com/beemdevelopment/aegis/ThemeMap.java
- app/src/main/java/com/beemdevelopment/aegis/ui/ScannerActivity.java
- app/src/main/res/values/styles.xml
Fixes #658.
The current full screen style does not support the Dark and AMOLED themes. This change adds two new full screen themes, `AppTheme.Fullscreen.Dark` and `AppTheme.Fullscreen.TrueBlack`. A new ThemeMap is added, `FULLSCREEN`, which is now  used by the ScannerActivity to set an appropriately themed full screen style.
I would have preferred to simply merge the existing `AppTheme.Fullscreen` style with an appropriate `DEFAULT` ThemeMap value but I could not find a way to merge two styles together, nor apply multiple styles at the same time. Additionally, since style inheritance is limited to a single parent, I could not inherit from more than one style when creating the new full screen styles. The end result is that some style items had to be manually copied across (I opted to copy …
> Add dark theme variants of the fullscreen style

- app/src/main/java/com/beemdevelopment/aegis/otp/GoogleAuthInfo.java
- app/src/main/java/com/beemdevelopment/aegis/otp/GoogleAuthInfoException.java
- app/src/main/java/com/beemdevelopment/aegis/ui/ScannerActivity.java
- app/src/main/res/values/strings.xml
Sometimes users get confused when they're trying to scan a Microsoft Authenticator QR code and think the error occurs because of a bug in Aegis.
> Show a clearer error message when encountering phonefactor:// URI's

- app/src/main/java/com/beemdevelopment/aegis/vault/VaultManager.java
Apparently ``toString()`` doesn't produce the same result on every platform.
Fixes #660.
> Use name() instead of toString() on StandardCharsets.UTF_8

- app/build.gradle
It looks like we broke the Authenticator Plus importer in
d660fbc6d1aa2facfa5358d38782d92b80cb769f by upgrading zip4j. So this patch
downgrades it again. I couldn't immediately find this issue in their issue
tracker, so it may be worth spending some time reporting this to them later.
Fixes #665.
> Downgrade zip4j to 2.6.0

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/beemdevelopment/aegis/AegisApplication.java
- app/src/main/java/com/beemdevelopment/aegis/AegisBackupAgent.java
- app/src/main/java/com/beemdevelopment/aegis/Preferences.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/BackupsPreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/SecurityPreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultManager.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/backup_rules.xml
- app/src/main/res/xml/preferences_backups.xml
This adds an option for participating in Android's backup system. Two items are
backed up: the ``files/aegis.json`` file and the entire ``shared_prefs``
directory. The option is disabled by default and can only be enabled if
encryption is enabled as well.
I tested this with Local Transport and Seedvault. To test with Local Transport,
see: https://developer.android.com/guide/topics/data/testingbackup.
Close #544.
> Add support for participating in Android's backup system

- app/src/main/java/com/beemdevelopment/aegis/ui/AegisActivity.java
This is an attempt to solve #714.
Is there any reason that you are using `finishAndRemoveTask` instead of `finish`? With this change everything behaves as expected: The app locks properly yet it remains in the recent app list.
> Fixed that app vanished from recent apps list after locking

- app/src/main/java/com/beemdevelopment/aegis/Preferences.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/BehaviorPreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryHolder.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences_behavior.xml
I implemented the pause feature discussed in #789.
You can enable this new feature in the settings menu under "Behavior" > "Freeze tokens when tapped". I tested it a bit and everything works as I would like it to.
Things that I'm not quite sure of:
- Explanation in settings might not be the best to describe what the feature does?
- Maybe we should add an icon next to a frozen token to inform the user that the token is outdated/paused?
What do you think?
> Option to Disable Automatic Refresh for Selected Code

- docs/vault.md
While I was developing a software to decrypt an aegis vault I stumbled upon an inconsistency in vault.md file.
In [vault.md](https://github.com/beemdevelopment/Aegis/blob/master/docs/vault.md#slots-1) the identifier for biometric is 0x01 and password is 0x02, but in [Slot.java](https://github.com/beemdevelopment/Aegis/blob/master/app/src/main/java/com/beemdevelopment/aegis/vault/slots/Slot.java#L28) the slots values are inverted. Also in [decrypt.py](https://github.com/beemdevelopment/Aegis/blob/master/docs/decrypt.py#L41) slots with type 1 are used to fetch password slots
> Vauld.md inconsistency fix

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/beemdevelopment/aegis/importers/DatabaseImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/DuoImporter.java
- app/src/main/res/values-ru-rRU/strings.xml
- app/src/main/res/values-uk-rUA/strings.xml
- app/src/main/res/values/strings.xml
Hey there!
This PR adds [DUO Mobile](https://play.google.com/store/apps/details?id=com.duosecurity.duomobile) OTP importer.
PS: I added translations in the languages I knew; please let me know if it's not the right way of contributing translations.
#68
> Add DUO importer

- app/src/main/java/com/beemdevelopment/aegis/importers/AegisImporter.java
- app/src/main/res/values/strings.xml
Import password prompt string is unclear #784 
This is just a minor dialog title text fix for Aegis imports. It changes the text from "Please enter a password" to "Please enter the import password" to make it more clear
I've added a string to the strings.xml (enter_password_aegis_title) and passed that to the AegisImporter.java decrypt() method, and passed (0) for the messageId parameter
> Fix Aegis import dialog message title

- app/src/androidTest/java/com/beemdevelopment/aegis/OverallTest.java
- app/src/main/java/com/beemdevelopment/aegis/crypto/otp/HOTP.java
- app/src/main/java/com/beemdevelopment/aegis/crypto/otp/YAOTP.java
- app/src/main/java/com/beemdevelopment/aegis/otp/GoogleAuthInfo.java
- app/src/main/java/com/beemdevelopment/aegis/otp/OtpInfo.java
- app/src/main/java/com/beemdevelopment/aegis/otp/YandexInfo.java
- app/src/main/java/com/beemdevelopment/aegis/ui/EditEntryActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryHolder.java
- app/src/main/java/com/beemdevelopment/aegis/util/YandexUtils.java
- app/src/main/res/drawable/ic_baseline_fiber_pin_24.xml
- app/src/main/res/layout/activity_edit_entry.xml
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/com/beemdevelopment/aegis/crypto/otp/YAOTPTest.java
- app/src/test/java/com/beemdevelopment/aegis/util/YandexUtilsTest.java
**Issue**: #617
**Based on**: https://github.com/norblik/KeeYaOtp 
This PR adds support for **Yandex.OTP** and some simple tests. Implementation does not require connection to Yandex servers to work. Made this, because original Yandex.Key app is kinda messy and has an extremely user-unfriendly UI.
The RFC of the protocol has not yet been published, but someone (the original solution) has made an implementation of it.
Soo, it's our time to shine and make most progressive Android OTP app ;)
**Important:** 
Yandex OTP protocol requires not only **secret**, but also **PIN** to work properly. That's why I had to put an additional field to `EntryEditActivity`. 
<details>
<summary>Screenshots</summary>
</details>
<details>
<summary>Compare to original Yandex.Key</summary>
</details>
<details> …
> Feature: Add Yandex OTP support

- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
Fix #921
Another possible approach is to check if there are any selected elements before the switch instruction:
```
@Override  
public boolean onActionItemClicked(ActionMode mode, MenuItem item) {
if(_selectedEntries.size() == 0) {
mode.finish();
return true;
}
switch (item.getItemId()) {
...
```
> Avoid crash when double clicking on "Copy" button

- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
Modify reason:
When the search box is expanded, part of the menu space on the right side is occupied. It is suggested that when the search box is expanded, the entire width of the toolbar is occupied (the search box has been opened by the customer, so just focus on the search task).
Another thinking solution: determine the width of the toolbar, if the width of the toolbar is less than a certain value, then expand the search box to all. This may be beneficial for large-screen devices.
Current:
After modification:
> Set the searchview to occupy all Toolbar widths when it expands

- app/src/main/java/com/beemdevelopment/aegis/otp/GoogleAuthInfo.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/dialogs/Dialogs.java
- app/src/main/res/values/strings.xml
Had a look at #933 
This proposed fix minimises code duplication by passing the image scan uri result to the scanner activity as an extra. While this clearly needs improvement in error handling, I am submitting as is to check if this is an acceptable approach before putting more work in.
Also to consider, should the UX require all images of export codes at once like the camera equivalent or allow importing 1 image at a time and just displaying a message explaining which part has been imported?
> Import Google Authenticator exports by image

- app/src/main/java/com/beemdevelopment/aegis/Preferences.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/AppearancePreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryHolder.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences_appearance.xml
#480 
Adds options to display codes in groups of 2, 3, and 4 as well as splitting codes in half or not at all.
> Additional code grouping options

- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
It seems sensible to do this since otherwise you end up incrementing the token blindly, and wondering whether it is working.
> Reveal hidden code on HOTP increment click

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/beemdevelopment/aegis/importers/BattleNetImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/DatabaseImporter.java
- app/src/main/res/values/strings.xml
- app/src/test/java/com/beemdevelopment/aegis/importers/DatabaseImporterTest.java
- app/src/test/java/com/beemdevelopment/aegis/vectors/VaultEntries.java
- app/src/test/resources/com/beemdevelopment/aegis/importers/battle_net_authenticator.xml
This PR is to add Battle.NET Authenticator importing support to Aegis which grabs the secret from the app "Battle.net Authenticator" with an id of `com.blizzard.bma` from `/data/data/com.blizzard.bma/shared_prefs/com.blizzard.bma.AUTH_STORE.xml`. Should satisfy the first request of issue #483 although based on the comments, that might be the only request Aegis is willing to do (When I read the comments it sounded like the other 2 require the internet permission).
Closes #483.
> Battle.net Authenticator Import Support

- app/src/main/java/com/beemdevelopment/aegis/ui/AuthActivity.java
- app/src/main/res/values/strings.xml
We are receiving **a lot** of reports from people thinking that Aegis doesn't open biometrics unlock by default (ie #1159, #1155, #1151 and lots more). These users are unaware that this is caused by our password reminder encouraging them to enter their password. The password reminder doesn't tell the users that Aegis defaults back to biometrics unlock after entering their password once which is why we made #989.
This pull requests adds an additional dialog whenever a user clicks on the "biometrics" button below the password field when the password reminder is active as shown below:
The screenshot above shows old text. The new text is:
> **_Biometric unlock by default_**
> _We occasionally prompt you to enter your password instead to ensure you haven\'t forgotten it and won\'t get locked …
> Add dialog when password reminder is active

- app/src/main/java/com/beemdevelopment/aegis/Preferences.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/AppearancePreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences_appearance.xml
This pull requests adds the ability to only show account names when they share the same issuer (considered "necessary").
[<img width=350 alt="Screenshot 5"
src="https://github.com/beemdevelopment/Aegis/assets/7524012/c16226b8-49ee-4432-b8cf-9139d32769d8">](https://github.com/beemdevelopment/Aegis/assets/7524012/c16226b8-49ee-4432-b8cf-9139d32769d8) [<img width=350 alt="Screenshot 5"
src="https://github.com/beemdevelopment/Aegis/assets/7524012/3d7eff8f-59ac-4a1e-835d-f407250fc76b">](https://github.com/beemdevelopment/Aegis/assets/7524012/3d7eff8f-59ac-4a1e-835d-f407250fc76b)
I used "onlyShowNecessaryAccountNames" as name for the boolean; I'm not too happy with it but I also couldn't find a better name. Feel free to suggest better alternatives.
This fixes #1117.
> Add ability to only show names when necessary

- app/src/main/java/com/beemdevelopment/aegis/helpers/AnimationsHelper.java
- app/src/main/java/com/beemdevelopment/aegis/ui/EditEntryActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/IconPacksManagerFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/PreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/intro/IntroBaseActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryHolder.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/TotpProgressBar.java
- app/src/main/res/layout/fragment_entry_list_view.xml
This pull request adds logic to properly respect the systems animation settings. Since I had to go through all the different animations we currently have in our app there is a possibility I might have missed one, let me know in case I did.
Fixes #930.
> Respect system animation setting

- app/src/main/java/com/beemdevelopment/aegis/ui/ImportEntriesActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/ImportEntriesAdapter.java
- app/src/main/res/values/strings.xml
This pull request adds the ability to automatically skip **potential** duplicates whenever Aegis detects import entries that share the same issuer and secret with a token that's already in the vault. The goal of this feature is to simplify the import process as requested in #453 and #1150.
[<img width=350 alt="Screenshot"
src="https://github.com/beemdevelopment/Aegis/assets/7524012/76f3dfc8-7539-4321-a734-1663fc88b8c6">](https://github.com/beemdevelopment/Aegis/assets/7524012/76f3dfc8-7539-4321-a734-1663fc88b8c6)
Closes #453. Closes #1150.
> Add ability to skip duplicates during import

- app/src/main/java/com/beemdevelopment/aegis/ui/AuthActivity.java
This PR fixes a bug that was introduced in #1163 which causes the 'biometrics' button on the unlock screen to be unresponsive.
Closes #1174
> Fix biometrics unlock button on AuthActivity

- app/src/main/java/com/beemdevelopment/aegis/icons/IconPack.java
- app/src/main/java/com/beemdevelopment/aegis/ui/EditEntryActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/IconAdapter.java
- docs/iconpacks.md
This introduces a new (optional) 'name' field for iconpack icons. It will be used to describe the icon in the icon selection dialog. If it is not present, the name of the icon will be derived from the filename, like before. Using this new field allows usage of more exotic characters in the icon name that are not allowed in a filename.
Related: https://github.com/aegis-icons/aegis-icons/pull/796
> Introduce optional 'name' field for iconpack icons

- app/src/main/java/com/beemdevelopment/aegis/services/LaunchAppTileService.java
- app/src/main/java/com/beemdevelopment/aegis/services/LaunchScannerTileService.java
Apparently ``getQsTile()`` can return null, which resulted in a crash. Reported through the Google Play Console:
```
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'void android.service.quicksettings.Tile.setState(int)' on a null object reference
at com.beemdevelopment.aegis.services.LaunchAppTileService.onStartListening
at android.service.quicksettings.TileService$H.handleMessage (TileService.java:488)
at android.os.Handler.dispatchMessage (Handler.java:106)
at android.os.Looper.loopOnce (Looper.java:205)
at android.os.Looper.loop (Looper.java:294)
at android.app.ActivityThread.main (ActivityThread.java:8177)
at java.lang.reflect.Method.invoke
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:552)
at …
```
> Check for null returned by getQsTile()

- app/src/main/res/layout/fragment_welcome_slide.xml
- app/src/main/res/values/strings.xml
Some users understandably get confused when they try to import a backup file from a different 2FA app during the intro and then get greeted with an error dialog.
This changes the button text to "Import Aegis vault" and adds a small hint text in the hope that this makes the limitations of the intro more clear to the user.
> Clarify that only Aegis vaults can be imported during the intro

- app/src/main/java/com/beemdevelopment/aegis/ui/GroupManagerActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/IconPacksManagerFragment.java
- app/src/main/res/layout/activity_groups.xml
- app/src/main/res/layout/fragment_icon_packs.xml
Wrapping a ``RecyclerView`` with a ``NestedScrollView`` breaks its recycling functionality because the view height is stretched to fit the full list of entries.
We never noticed performance issues in these two cases because these lists never get very long. Let's fix these cases anyway so that we don't accidentally base a new use of a ``RecyclerView`` on this broken pattern.
Also renamed ``list_slots`` to ``list_groups``. Must have been a copy-paste error.
> Never wrap RecyclerView with a NestedScrollView

- app/src/main/java/com/beemdevelopment/aegis/ui/EditEntryActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryHolder.java
This patch addresses two issues:
- The entry selection icon would flicker when a non-1x animator duration scale was set.
- The advanced entry field animation was not shown if the animator duration scale was set to .5x, due to a rounding error.
Introduced in: 9ff8efab69ec43c16cce41553ab3239a6613a050
> Fix two issues related to animation duration scale

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/beemdevelopment/aegis/ui/AssignIconsActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/ImportEntriesActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/res/layout/activity_assign_icons.xml
- app/src/main/res/menu/menu_assign_icons.xml
Apparently this was using ``menu_groups``, probably a copy-paste error.
This also moves ``AssignIconsActivity`` to the right package.
> Introduce a separate menu for AssignIconsActivity

- app/src/main/java/com/beemdevelopment/aegis/ui/dialogs/ChangelogDialog.java
- app/src/main/java/com/beemdevelopment/aegis/ui/dialogs/LicenseDialog.java
Hey all - I just made a PR to fix #1231 vs adding a proposal first since it was a very small and straightforward fix. This PR marks `SimpleWebViewDialog` implementers with public constructors instead of private, so that they can be recreated automatically on a configuration change (circumventing and fixing the linked crash). 
Let me know if there's anything else I should be adding here. Thanks!
> #1231 - Fix crash in License and Changelog dialogs on configuration change

- app/src/main/java/com/beemdevelopment/aegis/Preferences.java
- app/src/main/java/com/beemdevelopment/aegis/ui/dialogs/Dialogs.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultBackupManager.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultBackupPermissionException.java
- app/src/main/res/values/strings.xml
Users understandably get confused by the "No persisted URI permissions" error. This patch adds some text to the dialog explaining why this happened and how the user can fix the issue.
This permission issue can happen for one of two reasons:
- The user made a change to the backup destination (renamed, moved, deleted, etc)
- Aegis was restored from an Android backup
Closes #1230.
> Explain vault backup permission error

- app/src/main/java/com/beemdevelopment/aegis/ui/EditEntryActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/BackupsPreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/IconPacksManagerFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/ImportExportPreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/PreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/slides/WelcomeSlide.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultManager.java
Hi Aegis team,
this PR can hopefully finally close https://github.com/beemdevelopment/Aegis/issues/807.  
As https://github.com/beemdevelopment/Aegis/pull/998 didn't come to a merge, maybe we can tackle that once again.
Things to discuss:
- Do we want to replace the non-deprecated "Activity.startActivityForResult" as well? It is not marked deprecated in the code as we cast some Activities to an "android.app.Activity" instead of using the original "androidx.appcompat.app.AppCompatActivity". But the issue of best-practice still persists.
Example: https://github.com/cyb3rko/aegis/blob/9ad3a7925f0e8e980b7eb88ca7cdffbd1c8cb85d/app/src/main/java/com/beemdevelopment/aegis/ui/EditEntryActivity.java#L492 which is defined here https://github.com/cyb3rko/aegis/blob/9ad3a7925f0e8e980b7eb88ca7cdffbd1c8 …
> Replace deprecated startActivityForResult

- app/src/main/res/values/strings.xml
> feat: Update references to FreeOTP and add version hint "1.x"

- app/src/main/java/com/beemdevelopment/aegis/icons/IconPack.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/IconAdapter.java
Icon packs may have very generic issuers for their icons (like [aegis-simple-icons](https://github.com/alexbakker/aegis-simple-icons)). For example, this causes the icon assigning view to suggest the "C" icon for every entry that contains a "c".
This patch addresses that by giving inverse matches (where the entry issuer contains the icon issuer) a lower position in the suggested icons list.
> Prioritize normal icon issuer matches over inverse matches

- app/src/main/java/com/beemdevelopment/aegis/ui/AuthActivity.java
This prevents a crash that could occur when double tapping the Unlock button.
> Disable the unlock button until the slot decryption task is done

- app/src/androidTest/java/com/beemdevelopment/aegis/PanicTriggerTest.java
- app/src/main/java/com/beemdevelopment/aegis/ui/AuthActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/IntroActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultManager.java
This trades performance for making VaultManager a bit easier to reason about.
This also fixes a rare crash that could occur if the user retries to unlock the app after the previous attempt resulted in an error related to parsing the vault. The vault file would no longer be present in memory after the first attempt, causing the second attempt to crash the app.
> Load vault file on demand instead of juggling it around in-memory

- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
This should fix the following crash:
```
Exception java.lang.IndexOutOfBoundsException: setSpan (-1 ... 0) starts before 0
at android.text.SpannableStringInternal.checkRange (SpannableStringInternal.java:499)
at android.text.SpannableStringInternal.setSpan (SpannableStringInternal.java:199)
at android.text.SpannableStringInternal.setSpan (SpannableStringInternal.java:186)
at android.text.SpannableString.setSpan (SpannableString.java:60)
at com.beemdevelopment.aegis.ui.views.EntryAdapter$FooterView.refresh (EntryAdapter.java:596)
```
> Only bold number of shown entries if found in the translated string

- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
This fixes an issue where the entry list items no longer animated upon move, insert, delete, etc.
RecyclerView's DefaultItemAnimator automatically scales the animations according to the user's settings.
Introduced in 9ff8efab69ec43c16cce41553ab3239a6613a050
> Restore entry list item animations

- app/src/main/java/com/beemdevelopment/aegis/vault/VaultManager.java
In rare cases where writing to disk fails after the intro, a crash could occur if the user presses "Done" again. VaultManager would have been initialized, and trying to initialize it again would result in a crash.
> Don't initialize VaultManager after the intro unless saving succeeds

- app/src/main/java/com/beemdevelopment/aegis/ui/AegisActivity.java
- app/src/main/res/values/themes.xml
Previously, the dark background colors would not be applied for this combination of settings.
Unfortunately, I couldn't find a way to avoid some duplication in themes.xml.
> Apply dark background colors when combining AMOLED and dynamic colors

- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryHolder.java
- app/src/main/res/anim/slide_down_fade_in.xml
- app/src/main/res/layout/card_entry.xml
- app/src/main/res/layout/card_entry_compact.xml
- app/src/main/res/layout/card_entry_small.xml
This pull request fixes the "copied" animation which became invisible after our material 3 changes.
Not the best fix, but it works in all scenarios (account name placement, view modes etc).
> Fix copied text visibility

- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
- app/src/main/res/layout/activity_edit_entry.xml
This pull request fixes the progressbar uniformity and the weird spacing around the Group field in the Edit Entry view.
I've added the uniformity check to the search filter. And from now on whenever there's only 1 shown entry, the perioduniformity check will now return the period of that single entry.
Fixes #1306
> Fix a couple UI inconsistencies

- app/src/main/java/com/beemdevelopment/aegis/Preferences.java
- app/src/main/java/com/beemdevelopment/aegis/SortCategory.java
- app/src/main/java/com/beemdevelopment/aegis/helpers/comparators/LastUsedComparator.java
- app/src/main/java/com/beemdevelopment/aegis/ui/EditEntryActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultEntry.java
- app/src/main/res/layout/activity_edit_entry.xml
- app/src/main/res/menu/menu_main.xml
- app/src/main/res/values/strings.xml
This PR adds the ability to save last used timestamps into our preferences, just like we do for the usage count. We probably should find a better way to combine both usage counts and the last used timestamps but I think this will suffice for now. I also added the ability to sort based on this timestamp. Do note (and I actually prefer it this way) that the sorting for the 'last used' entry only triggers whenever we refresh the list, it won't immediately trigger as soon as you 'use' the entry.
Closes #1089
> Add ability to sort based on last used timestamp

- app/src/main/java/com/beemdevelopment/aegis/ViewMode.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
This patch addresses the following:
- More consistent offsets between entries in the list, especially in relation to the action bar and the error card.
- Consistent correct application of card shapes when switching between favoriting and unfavoriting entries.
- Removal of CompactDividerDecoration. We no longer uses dividers, so this is no longer needed.
Example before and after:
> Fix various minor inconsistencies in entry list item offsets

- app/src/main/res/values/themes.xml
My best guess is that API 28 and below somehow interpret ``#000000`` to mean either ``@null`` or transparent for ``android:colorBackground``.
Fixes #1325.
> Use Android color reference for android:colorBackground in AMOLED theme

- app/src/main/AndroidManifest.xml
- app/src/main/res/values/themes.xml
This reduces the chance that we flashbang the user when they launch the app. The issue remains on older Android versions that don't natively support dark mode, but I don't think that's fixable.
Activities override the theme based on the user's settings, so this change only has effect while the app is launching.
Fixes #1330.
> Use DayNight as the default theme

- app/src/main/java/com/beemdevelopment/aegis/helpers/PasswordStrengthHelper.java
- app/src/main/java/com/beemdevelopment/aegis/ui/dialogs/Dialogs.java
- app/src/main/java/com/beemdevelopment/aegis/ui/slides/SecuritySetupSlide.java
- app/src/main/res/values/strings.xml
This should help reduce the chance that zxcvbn4j explodes on a password input.
I also took the opportunity to deduplicate related code a bit.
> Stop analyzing password strength if it becomes longer than 64 chars

- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesActivity.java
Fixes #1346
`_prefTitle` is saved in the bundle as `CharSequence`
we only able to store `CharSequence` since `Preference.getTitleRes` is removed in AndroidX. 
As a workaround, we update the title again on Fragment.onStart()
https://github.com/beemdevelopment/Aegis/assets/11408319/b929ddf9-b8fb-4ce2-89cf-25ac2b433491
> Fix Language of Appearance Title

- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/AppearancePreferencesFragment.java
When I change in the preferences the "Code digit grouping" from x to y and then open the dialog again, the displayed value is still x instead of y. This PR fixed this issue, that is, it displays y when re-opening the dialog
> Update change of Code Digit Grouping

- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
- app/src/main/res/layout/dialog_select_groups.xml
Resolves #755
PR Continution #841
> Fix Scrolling in BottomSheet

- app/src/main/java/com/beemdevelopment/aegis/importers/DatabaseImporter.java
Thanks for making a nice 2FA app!
I tried Aegis while being frustrated by FreeOTP (backup won't import on new phone).
I was briefly excited about Aegis listing "FreeOTP" in the import-dropdown, but later disappointed to learn it is only for the old 1.x format.
To spare others the same emotional rollercoaster, I'm suggesting that the dropdown _itself_ should already mention "FreeOTP **(1.x)**"
This passes local unit tests, and looks correct in the device emulator:
See also:
- #1204, where the 1.x-hint was introduced
- #1084: tracking issue for 2.x support
- https://github.com/freeotp/freeotp-android/issues/381 FreeOTP-issue to reconsider the brittle serialised java format used by 2.x
> DatabaseImporter: add overlooked FreeOTP "1.x" hint

- app/src/main/java/com/beemdevelopment/aegis/importers/DatabaseImporter.java
Hi again! After the mini-fix in #1408, I've been toying with FreeOTP+, and syncing it with Aegis.
(Confirming that the FreeOTP+ backup works, after being burned by FreeOTP, never again!)
FreeOTP+ offers two export formats: JSON and URI.
Aegis imports only the JSON, and gives a "cryptic" (for non-developers) "couldn't deserialise java.lang.String to JsonObject" error if you try to import the URI-format.
This PR makes the JSON-format explicit in the importer dropdown, and updates the few translations of the additional-hint-text that I'm personally comfortable with.
I hope your translation community will step up for the rest, but since the dropdown is untranslated, everybody should benefit even without the hint-texts.
I'm not sure if URI-import support is something that is desired. I don't …
> Clarify FreeOTP+ import needs JSON, not URI-format

- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
This fixes an issue introduced by 46e1421c28857034c135f3c3facbe8b9b5c6483d where the group chip would not show after unlocking Aegis. This happened because the activity result is received *after* ``onStart``. When we were using ``onResume``, it was the other way around.
> Initialize the group chip properly after unlocking Aegis

- app/src/main/java/com/beemdevelopment/aegis/ui/EditEntryActivity.java
- app/src/main/res/layout/activity_edit_entry.xml
This slightly simplifies the approach we use to animate the advanced entry settings into view, by defaulting its alpha to 0 and setting it to VISIBLE before the animation starts. That way, we're not dependent on "animation ended" callbacks that apparently don't fire in all cases.
The XML diff looks a bit scary, but it basically just removes a wrapping ``RelativeLayout`` that appears to not be necessary.
Fixes #1417.
> Simplify approach for animating advanced entry settings

- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
This fixes an issue introduced by 46e1421c28857034c135f3c3facbe8b9b5c6483d where the automatic time sync dialog would be shown multiple times. After decrypting the vault, completing the setup wizard and right before loading the entries in the onStart. I removed the dialog from both the IntroResult and DecryptResult. 
Fixes #1436
> Fix showing duplicate time sync dialogs

- app/src/main/java/com/beemdevelopment/aegis/ui/AuthActivity.java
This is another attempt to fix a rare crash we're seeing in the developer console:
```
Exception android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
at android.view.ViewRootImpl.setView (ViewRootImpl.java:1423)
at android.view.WindowManagerGlobal.addView (WindowManagerGlobal.java:408)
at android.view.WindowManagerImpl.addView (WindowManagerImpl.java:148)
at android.widget.PopupWindow.invokePopup (PopupWindow.java:1583)
at android.widget.PopupWindow.showAsDropDown (PopupWindow.java:1430)
at android.widget.PopupWindow.showAsDropDown (PopupWindow.java:1386)
at com.beemdevelopment.aegis.ui.AuthActivity.lambda$showPasswordReminder$5 (AuthActivity.java:253)
at android.os.Handler.handleCallback (Handler.java:942)
at …
```
> Add an extra check before showing the password reminder popup

- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/AppearancePreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryHolder.java
- app/src/main/res/layout/card_entry_tile.xml
- app/src/main/res/values/strings.xml
This PR removes the limitation to refrain the user from setting the account name to hidden whenever the Tiles mode is being used. We still override the account name position preference it's set to "Next to issuer" since that will make a mess in Tiles mode.
We would have to think about a nice way to handle all the different customization options between the different viewmodes though.
Fixes #1285
> Add ability to hide account name in tiles mode

- app/src/main/java/com/beemdevelopment/aegis/helpers/CenterVerticalSpan.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryHolder.java
This fixes the weird obnoxiously big dots that could happen when using different fonts/languages #1012
It's definitely not perfect and needs extensive testing, but it's something.
Before:
After:
Fixes #1012.
Fixes #790.
> Fix sizing inconsistency of the dots in hidden view

- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/AuditLogPreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/AuditLogHolder.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultRepository.java
- app/src/main/res/values/strings.xml
This fixes the following crash I noticed in the developer console:
```
Exception java.lang.AssertionError:
at com.beemdevelopment.aegis.util.UUIDMap.getByUUID (UUIDMap.java:127)
at com.beemdevelopment.aegis.vault.VaultRepository.getEntryByUUID (VaultRepository.java:229)
at com.beemdevelopment.aegis.ui.fragments.preferences.AuditLogPreferencesFragment.lambda$onViewCreated$0 (AuditLogPreferencesFragment.java:70)
at androidx.lifecycle.LiveData.considerNotify (LiveData.java:133)
at androidx.lifecycle.LiveData.dispatchingValue (LiveData.java:151)
at androidx.lifecycle.LiveData.setValue (LiveData.java:309)
at androidx.lifecycle.LiveData$1.run (LiveData.java:93)
at android.os.Handler.handleCallback (Handler.java:959)
at android.os.Handler.dispatchMessage (Handler.java:100)
at …
```
> Account for audit log entries that reference deleted entries

- app/src/main/java/com/beemdevelopment/aegis/Preferences.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/BehaviorPreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences_behavior.xml
This pull request adds the ability to change what fields are used within our search filter. 
Closes #1314
> Add preference to change search behavior

- app/src/main/res/drawable/progress_horizontal.xml
Very minor PR, but I think a rounded progressbar fits Material 3 better:
> Make progressbar rounded on the right side

- app/src/main/java/com/beemdevelopment/aegis/ui/GroupManagerActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/GroupAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultRepository.java
- app/src/main/res/layout/card_group.xml
After I built #1479 it only made more sense to me to add the ability to reorder groups through the GroupManagerActivity via drag and drop. This allows the user to change the order in which the groups will show up in the action bar.
This PR also removes the need to keep a list of renamed groups since this feature replaces all the groups with the updated collection.
> Add ability to reorder groups

- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/IconPacksManagerFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/IconPackAdapter.java
The following crash could occur when trying to import an icon pack for which an empty folder still exists on disk:
```
Exception java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 1
at jdk.internal.util.Preconditions.outOfBounds (Preconditions.java:64)
at jdk.internal.util.Preconditions.outOfBoundsCheckIndex (Preconditions.java:70)
at jdk.internal.util.Preconditions.checkIndex (Preconditions.java:266)
at java.util.Objects.checkIndex (Objects.java:359)
at java.util.ArrayList.remove (ArrayList.java:511)
at com.beemdevelopment.aegis.ui.views.IconPackAdapter.removeIconPack (IconPackAdapter.java:38)
at com.beemdevelopment.aegis.ui.fragments.preferences.IconPacksManagerFragment.removeIconPack (IconPacksManagerFragment.java:158)
at …
```
> Fix a crash that could occur when deleting a broken icon pack import

- app/src/androidTest/java/com/beemdevelopment/aegis/OverallTest.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/dialog_select_groups.xml
- app/src/main/res/layout/fragment_entry_list_view.xml
- app/src/main/res/values/strings.xml
This PR moves the group filters from the EntryListView to the MainActivity as shown in the screenshots below.
Tapping the "All" placeholder group will uncheck all the groups and set the filter to null.
Changing the filter will make a 'Save' button appear at the end of row to set the selected filter as default.
I'm not entirely sure if the "Save" button at the end of the row is intuitive since it will be quite hidden for our users with less screen estate or with a lot of groups, but I think it does the job for now and we can always look into this in the future.
Fixes #1406
Fixes #914
Closes #628
Closes #1219
> Improve group filters

- app/src/main/res/layout/activity_edit_entry.xml
- app/src/main/res/layout/dialog_text_input.xml
One thing that always slightly bothered me in Aegis was the lack of capitalization in our different text fields. Name, Issuer, Note, New Group were always lowercase. This PR capitalizes the first word of every sentence in our generic text fields inside of a dialog or in the aforementioned text fields. The user can always override this by manually pressing the shift key on their keyboard.
> Fix capitalization of multiple text fields

- app/src/main/java/com/beemdevelopment/aegis/Preferences.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/AppearancePreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryHolder.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences_appearance.xml
This PR adds a toggle under Settings -> Appearance to show when codes are about to expire. We will fade the color of the codes to a bright red when they're expiring in 7 seconds. Then when 3 seconds are left the codes will start to 'blink' as shown in the video below.
Fixes #411 
https://github.com/user-attachments/assets/4a5898de-a562-4a2d-9d04-640dae8b3bce
> Show when codes are about to expire

- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/res/layout/dialog_select_group.xml
- app/src/main/res/menu/menu_action_mode.xml
- app/src/main/res/values/strings.xml
Since we've heavily improved our group management it would only make sense to also improve the flow in which our users assign groups to their entries. This PR adds the ability to tap 'Assign group' whenever they have entries selected.
Fixes #597
https://github.com/user-attachments/assets/6883f4b2-1e55-4da6-b855-2cc65e454683
> Add ability to easily assign groups

- app/src/androidTest/java/com/beemdevelopment/aegis/OverallTest.java
- app/src/main/java/com/beemdevelopment/aegis/GroupPlaceholderType.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/ImportExportPreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/models/VaultGroupModel.java
- app/src/main/res/layout/activity_main.xml
As discussed and mentioned [here](https://github.com/beemdevelopment/Aegis/pull/1479#issuecomment-2354206113) and [here](https://github.com/beemdevelopment/Aegis/issues/914#issuecomment-2354110271) after #1479 was merged we decided to change the group filter to just a single selection as we think more users would prefer that. We might add support for multi-selection in the future but this will do for now.
As a bonus I also removed the animation when switching groups as it was quite obnoxious.
https://github.com/user-attachments/assets/234ddfb4-0e49-47a6-9340-2508ed7f0d38
> Change group filter to a single selection

- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/AppearancePreferencesFragment.java
Closes #1015 as this setting never worked on Marshmallow or below and never should've been visible on these versions in the first place. This was a bug that has been introduced in #288 🙃
> Fix visibility of locale setting on Marshmallow

- app/src/main/java/com/beemdevelopment/aegis/Preferences.java
- app/src/main/java/com/beemdevelopment/aegis/otp/TotpInfo.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryHolder.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
- app/src/main/res/layout/card_entry.xml
- app/src/main/res/layout/card_entry_compact.xml
- app/src/main/res/layout/card_entry_small.xml
- app/src/main/res/layout/card_entry_tile.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences_appearance.xml
We still don't really see the need for this feature but due to high demand we caved. This PR adds a separate toggle in the preferences which allows the user to see the next code under the current code. This has been on ongoing discussion for a while in #923 and it seems like there's a lot of different opinions about it.
> Add ability to show next code

- app/src/main/java/com/beemdevelopment/aegis/helpers/SimpleItemTouchHelperCallback.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/models/ErrorCardInfo.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultRepository.java
Gets rid of all of the custom logic we had for notifying the RecyclerView about changes in the entry list. This will allow for more simplifications in the future around non-persisted changes to state in the entry list.
A neat side effect is that any filtering/ordering changes in the entry list are now also animated: https://alexbakker.me/u/4a4ie5yzpj.mp4
This touches the fundamentals of the entry list, so lots of careful testing required.
Closes #1053.
> Use DiffUtil for the RecyclerView of the entry list

- app/src/main/java/com/beemdevelopment/aegis/BackupsVersioningStrategy.java
- app/src/main/java/com/beemdevelopment/aegis/Preferences.java
- app/src/main/java/com/beemdevelopment/aegis/ui/dialogs/Dialogs.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/BackupsPreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultBackupManager.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultManager.java
- app/src/main/res/layout/dialog_backups_versioning_strategy.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences_backups.xml
> Single backup

- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
This has been broken since 46e1421c28857034c135f3c3facbe8b9b5c6483d.
I also removed some other logic from ``onCreateOptionsMenu`` that doesn't seem to belong there anymore.
> Update sort category radio button state in the menu

- app/src/main/java/com/beemdevelopment/aegis/crypto/otp/YAOTP.java
- app/src/main/java/com/beemdevelopment/aegis/otp/MotpInfo.java
- app/src/main/java/com/beemdevelopment/aegis/otp/SteamInfo.java
- app/src/main/java/com/beemdevelopment/aegis/otp/TotpInfo.java
- app/src/main/java/com/beemdevelopment/aegis/otp/YandexInfo.java
- app/src/test/java/com/beemdevelopment/aegis/crypto/otp/YAOTPTest.java
This fixes an issue where Steam OTP's were displayed in the wrong format. The underlying issue has been present for a while, but it first became apparent in e4c9a584f48da402291608ec1db0983dcdee2fde.
Fixes #1537.
> Make subclasses of TotpInfo override only getOtp(long time)

- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
This PR improves the search feature as requested in #1527 and #1536. After this gets merged Aegis will:
1. Hide the group chips when user starts searching
2. Ignore the current active group filter
3. Matches now in all fields that are enabled to search in
Example: 
| Search Filter     | Issuer   | Name   | Match? |
|--------------------|----------|--------|--------|
| `GitHub michaelschattgen`     | GitHub   | michaelschattgen   | ✅ Yes  |
| `GitHub`          | GitHub   | michaelschattgen   | ✅ Yes  |
| `michaelschattgen`            | GitHub   | michaelschattgen   | ✅ Yes  |
| `hub michaelschattgen`        | GitHub   | michaelschattgen   | ✅ Yes   |
| `michaelschattgen Git`     | GitHub   | michaelschattgen   | ✅ Yes  |
| `Github e`         | GitHub   | michaelschattgen   | ✅ Yes    |
| …
> Improve search feature for better UX

- app/src/main/res/values/colors.xml
This PR fixes the contrast of the next code color. I've made some minor tweaks to contrast while also (try to) not making it too prominent.
Left is before, right is after this PR is merged:
Fixes #1556
> Improve contrast of next code color

- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
Turns out I was a little too enthusiastically removing things in 9d383b85d8c5581f12a1a22407ce4615c4d499f3. The menu may not necessarily have been created yet in all cases.
> Fix state updates for the lock and sort menu items

- app/src/main/java/com/beemdevelopment/aegis/helpers/ViewHelper.java
- app/src/main/java/com/beemdevelopment/aegis/ui/AboutActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/AssignIconsActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/EditEntryActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/GroupManagerActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/ImportEntriesActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/ScannerActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/TransferEntriesActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/AuditLogPreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/IconPacksManagerFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/PreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
- app/src/main/res/layout/activity_about.xml
- app/src/main/res/layout/fragment_audit_log.xml
- app/src/main/res/layout/fragment_entry_list_view.xml
To not have UI elements obscured by system bars on Android 15, this PR adds bottom padding to lists in the main vault view, preferences and about.
As for the AppBar, `android:fitsSystemWindows="true"` only makes the top insets get applied, so I had to manually apply the left and right ones as well. [Google seems to recommend](https://medium.com/androiddevelopers/insets-handling-tips-for-android-15s-edge-to-edge-enforcement-872774e8839b) using `ViewCompat.setOnApplyWindowInsetsListener` over `android:fitsSystemWindows` for this reason. (Tip 10)
Fixes #1549
> Apply window insets to accommodate system UI.

- app/src/main/AndroidManifest.xml
This is a temporary measure to help users who are stuck in a situation where they run into OOM conditions due to large icons in their vault file.
Relates to #1298.
> Set largeHeap to true in AndroidManifest

- app/src/androidTest/java/com/beemdevelopment/aegis/BackupExportTest.java
Do some basic tests of the html export code.
- Make sure that a file was created.
- Make sure that the file can be parsed by an xml parser without error.
- Make sure that the document tag is "html".
> add test for html exports

- app/src/main/java/com/beemdevelopment/aegis/ui/ImportEntriesActivity.java
- app/src/main/res/layout/activity_import_entries.xml
> Fix obstructing snackbar padding

- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryHolder.java
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/themes.xml
Difference before vs after:
I like this a lot better, please let me know if you have any suggestions.
Fixes #672
> Improve color contrast on hidden codes

- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/ImportExportPreferencesFragment.java
The previous logic was not an issue because FileOutputStream is unbuffered, but still, this is more correct.
> Flush temporary export file before starting ExportTask

- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
This fixes an issue where the item decoration may be wrong in some cases. For example, adding a new entry to the bottom of the list may not update the decoration of the item that was previously the last one in the list.
To reproduce, use this vault: https://alexbakker.me/u/mov4455gp5.json. Start without a group filter, apply sorting based on Issuer (A to Z) and enable group multiselect. Then:
- Tap the "Test" chip
- Tap the "Test2" chip
- Tap the "No group" chip
- Notice that the offset between the last 2 entries looks wrong: https://alexbakker.me/u/nedcyiro2q.png
Probably introduced in 9131cae944f354c95873aa1c257e87b0c9b1f210.
> Update divider decoration when filter/sort changes

- FAQ.md
> [FAQ] clarified about which password to use when importing your vault

- app/src/main/java/com/beemdevelopment/aegis/ui/EditEntryActivity.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultEntry.java
- app/src/main/res/drawable/ic_tag_24.xml
- app/src/main/res/layout/dialog_duplicate_entry.xml
- app/src/main/res/values/strings.xml
This PR adds a new BottomSheetDialog in the EditEntryActivity notifying the user that a similar entry (based on name + issuer) already exists.  We will prompt the user with a couple options on how to proceed. I purposely left out the "Save anyway" option because I don't see the need for it, but let me know if you'd like to see otherwise.
Closes #1606
> Add check for duplicates upon saving entry

- app/src/main/java/com/beemdevelopment/aegis/ui/AuthActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/components/NoAutofillEditText.java
- app/src/main/res/layout/activity_auth.xml
Didn't expect the initial issue to be this tacky to solve. Creating a custom EditText which sets AutofillType to AUTOFILL_TYPE_NONE seems to do the trick. Setting the AutofillType through xml unfortunately wasn't enough.
Closes #1672
> Add custom EditText to prevent Autofill service from popping up
