- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/strings.xml
- Removed unused strings
- Moved arrays to their own file, so translators do not have to deal with arrays
> Strings.xml cleanup

- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/res/drawable/ic_add_photo_24px.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/values/strings.xml
This commit will add the ability described in #61.
> Add ability to scan image for QR code

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/beemdevelopment/aegis/helpers/FabScrollHelper.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/SelectEntriesActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/models/ImportEntry.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/ImportEntriesAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/ImportEntryHolder.java
- app/src/main/res/drawable/ic_check_black_24dp.xml
- app/src/main/res/drawable/ic_done_all_black_24dp.xml
- app/src/main/res/layout/activity_select_entries.xml
- app/src/main/res/layout/card_import_entry.xml
- app/src/main/res/menu/menu_select_entries.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/strings.xml
> Add ability to select entries when importing

- app/src/main/java/com/beemdevelopment/aegis/crypto/CryptoUtils.java
- app/src/main/java/com/beemdevelopment/aegis/importers/AndOtpImporter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/Dialogs.java
- app/src/main/java/com/beemdevelopment/aegis/ui/EditEntryActivity.java
- app/src/main/res/layout/dialog_text_input.xml
This also refactors dialog_newgroup to serve as a generic text input dialog.
Depends on #71 and #73. Closes #46.
> Add support for importing encrypted andOTP backups

- app/src/main/java/com/beemdevelopment/aegis/Preferences.java
- app/src/main/java/com/beemdevelopment/aegis/SortCategory.java
- app/src/main/java/com/beemdevelopment/aegis/Theme.java
- app/src/main/java/com/beemdevelopment/aegis/ViewMode.java
- app/src/main/java/com/beemdevelopment/aegis/ui/AegisActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/SelectEntriesActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryHolder.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
- app/src/main/res/values/arrays.xml
This fixes the following bugs:
- Sort category is forgotten after lock/unlock
- The sort mode is not respected for new entries (#67)
I got a little carried away while working on this patch and also included the following other enhancements:
- Simplify the SortCategory, Theme and ViewMode enums
- Simplify usage of string resources
- Don't call notifyDataSetChanged and runLayoutAnimation unnecessarily
I'll make sure to separate unrelated changes next time.
> Fix the last couple of sorting bugs

- app/build.gradle
> Update Krop to 0.44

- app/src/main/java/com/beemdevelopment/aegis/ui/AuthActivity.java
> Select and focus password on failed unlock attempt

- app/src/main/java/com/beemdevelopment/aegis/helpers/EditTextHelper.java
- app/src/main/java/com/beemdevelopment/aegis/ui/EditEntryActivity.java
> Add possibility to ignore spaces in EditTexts

- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values/strings.xml
Updated french translation (added missing strings from last update).
I also added one single dot in english text.
This time the pull request is clean.
> Update french translation

- app/src/main/java/com/beemdevelopment/aegis/ui/tasks/SlotListTask.java
This makes sure the case where a user set up Aegis v0.4 with a password of over 64 bytes is also covered. It's an edge case I missed in 8c658ac93069b42c8db1e7cbe0da9c5882a7d5b1.
> Always try to decrypt the password slot first, before the fallback

- app/src/main/res/layout/activity_auth.xml
> Adapt the unlock button size in AuthActivity to the text width

- app/src/main/java/com/beemdevelopment/aegis/importers/AuthyImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/DatabaseImporter.java
This pull request adds the ability to import entries from Authy, which requires root. I had to do some ugly string hacks in order to set the correct issuer/account name. Authy's database files are a mess.
Closes #65
> Add support for importing from Authy

- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
- app/src/main/res/menu/menu_main.xml
- app/src/main/res/values/strings.xml
This pull request adds the ability to search for entries in the users' vault. This only supports searching for issuer for now but it won't be difficult to add more fields.
Closes #90
> Add ability to search for entries in vault

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/beemdevelopment/aegis/AegisApplication.java
- app/src/main/java/com/beemdevelopment/aegis/db/DatabaseManager.java
- app/src/main/java/com/beemdevelopment/aegis/services/NotificationService.java
- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
- app/src/main/res/values/strings.xml
> Add notification to warn user about the unlock state

- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
> Get external storage read permissions before selecting an image to scan

- app/src/main/res/layout/activity_auth.xml
> Add ability to toggle password visibility

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
> Add support for deeplinking otpauth uris

- app/src/main/java/com/beemdevelopment/aegis/importers/AegisImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/AndOtpImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/AuthyImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/DatabaseImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/FreeOtpImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/FreeOtpPlusImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/GoogleAuthImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/SteamImporter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/util/PreferenceParser.java
This also includes some other small changes:
- Make FreeOtpImporter more reusable
- Refactor preference file parsing logic into a separate class
- Add support for importing Steam tokens from FreeOTP(+)
- Make FileReader a bit leaner
- Add some missing @Override annotations
Closes #45.
> Add support for importing from FreeOTP+

- app/src/main/java/com/beemdevelopment/aegis/ui/EditEntryActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
> Set group on new entries automatically when group filter is active

- app/src/main/java/com/beemdevelopment/aegis/db/DatabaseEntry.java
- app/src/main/java/com/beemdevelopment/aegis/ui/EditEntryActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
I was also going to tackle #24, but I haven't figured out how to do that nicely yet, so that'll come later.
> Set a default value for period and digits for new entries

- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
- app/src/main/res/layout/fragment_entry_list_view.xml
- app/src/main/res/values/strings.xml
This pull request adds a empty data placeholder when no entries are found in the vault. This is a nice touch for when people just downloaded Aegis. Feel free to edit the text, I just made something up.
> Add placeholder for empty recyclerview

- app/build.gradle
- app/src/main/java/com/beemdevelopment/aegis/ui/AboutActivity.java
- app/src/main/res/layout/content_about.xml
- app/src/main/res/values/strings.xml
This will help us differentiate between custom/debug builds and release builds of Aegis. I also added an onClick listener to copy the version to the clipboard when the user taps it.
> Add git commit hash and branch information to AboutActivity for debug builds

- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
- app/src/main/res/values/strings.xml
This pull request adds an 'Ungrouped'-filter to show all entries without a group.
Closes #209
> Add ungrouped filter

- .travis.yml
- app/build.gradle
- app/src/main/java/com/beemdevelopment/aegis/AegisApplication.java
- app/src/main/java/com/beemdevelopment/aegis/ui/AboutActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
- app/src/main/res/values-zh/strings.xml
- app/src/main/res/values/styles.xml
- build.gradle
This also fixes an issue with the use of the Iconics library where it was initialized twice. I also removed the dependency to [AndroidX Preference eXtended](https://github.com/takisoft/preferencex-android), as there don't seem to be any issues with using the vanilla AndroidX preference library anymore.
> Target API 29, update gradle and update the dependencies

- app/src/main/java/com/beemdevelopment/aegis/importers/DatabaseImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/WinAuthImporter.java
> Add WinAuth importer

- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
> Add minor text improvement

- app/src/main/java/com/beemdevelopment/aegis/services/NotificationService.java
Fixes #217. I was able to reproduce the issue on an emulator with Android 6.0 and it's no longer present after applying this patch.
> Always cancel the persistent notification when the app task is removed

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
As we switched to the SAF, we don't need these permissions anymore.
> Remove EXTERNAL_STORAGE permissions

- app/src/main/java/com/beemdevelopment/aegis/ui/slides/CustomAuthenticationSlide.java
- app/src/main/res/layout/dialog_password.xml
- app/src/main/res/layout/fragment_authenticated_slide.xml
- app/src/main/res/layout/fragment_authentication_slide.xml
- app/src/main/res/values/strings.xml
This adds some extra explanation of the security options to the intro, as well
as a warning when setting a password.
[<img width=200 src="https://alexbakker.me/u/jipc03u3hx.png">](https://alexbakker.me/u/jipc03u3hx.png)
[<img width=200 src="https://alexbakker.me/u/uw9nbsd95s.png">](https://alexbakker.me/u/uw9nbsd95s.png)
[<img width=200 src="https://alexbakker.me/u/mdoe5m8c3o.png">](https://alexbakker.me/u/mdoe5m8c3o.png)
> Add explanation for the security options

- app/src/main/java/com/beemdevelopment/aegis/Preferences.java
- app/src/main/java/com/beemdevelopment/aegis/ui/AuthActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
- app/src/main/res/layout/popup_password.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
Instead of showing the reminder after x unlocks, I decided to show the reminder
2 weeks after the vault was last unlocked with the password. Let me know if you
agree with that.
[<img width=300 src="https://alexbakker.me/u/115z6be7go.png">](https://alexbakker.me/u/115z6be7go.png)
Closes #145.
> Remind users who use biometrics to enter their password periodically

- app/src/main/java/com/beemdevelopment/aegis/encoding/Base64.java
- app/src/main/java/com/beemdevelopment/aegis/importers/DatabaseImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/DatabaseImporterEntryException.java
- app/src/main/java/com/beemdevelopment/aegis/importers/TotpAuthenticatorImporter.java
- app/src/main/res/values/strings.xml
This is by far the most ridiculous format/'security' I've seen so far.
> Add support for importing from TOTP Authenticator

- app/src/main/java/com/beemdevelopment/aegis/importers/AuthyImporter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/Dialogs.java
- app/src/main/res/values/strings.xml
> Add support for importing encrypted and manually entered tokens from Authy

- app/src/main/res/values/strings.xml
> Change Capitalization

- app/src/main/java/com/beemdevelopment/aegis/vault/VaultManager.java
This adds a recovery mechanism for (probably extremely rare) cases where the app may be killed before it is finished writing the vault file to disk. In the example below, we see that AtomicFile moved ``aegis.json`` to ``aegis.json.bak`` before writing to ``aegis.json``.
```
bonito:/ # ls -lah /data/data/com.beemdevelopment.aegis.debug/files
total 27M
drwxrwx--x 2 u0_a306 u0_a306 3.4K 2020-02-02 13:22 .
drwx------ 6 u0_a306 u0_a306 3.4K 2020-02-01 19:51 ..
-rw------- 1 u0_a306 u0_a306  19M 2020-02-02 13:22 aegis.json
-rw------- 1 u0_a306 u0_a306  34M 2020-02-02 13:21 aegis.json.bak
```
Because the app was killed before it could finish writing, it is only 19M in size, instead of the expected 34M. The next time the app starts, AtomicFile will notice that the .bak file is still present, and …
> Protect writes of the vault file against corruption with AtomicFile

- app/src/main/java/com/beemdevelopment/aegis/otp/GoogleAuthInfo.java
- app/src/main/java/com/beemdevelopment/aegis/ui/ScannerActivity.java
> Make the parsing logic of the QR code URI more robust

- app/src/main/java/com/beemdevelopment/aegis/ui/Dialogs.java
- app/src/main/java/com/beemdevelopment/aegis/ui/slides/CustomAuthenticatedSlide.java
> Improve confirm password functionality

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/beemdevelopment/aegis/AegisApplication.java
- app/src/main/java/com/beemdevelopment/aegis/ui/EditEntryActivity.java
- app/src/main/res/values-cs-rCZ/strings.xml
- app/src/main/res/values-de-rDE/strings.xml
- app/src/main/res/values-es-rES/strings.xml
- app/src/main/res/values-fr-rFR/strings.xml
- app/src/main/res/values-it-rIT/strings.xml
- app/src/main/res/values-kn-rIN/strings.xml
- app/src/main/res/values-nl-rNL/strings.xml
- app/src/main/res/values-ru-rRU/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
> Rename "profile" text to "entry"

- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryHolder.java
- app/src/main/res/anim/fade_in.xml
- app/src/main/res/anim/fade_out.xml
- app/src/main/res/anim/slide_down_fade_in.xml
- app/src/main/res/anim/slide_down_fade_out.xml
- app/src/main/res/layout/card_entry.xml
- app/src/main/res/layout/card_entry_compact.xml
- app/src/main/res/layout/card_entry_small.xml
- app/src/main/res/values-cs-rCZ/strings.xml
- app/src/main/res/values-de-rDE/strings.xml
- app/src/main/res/values-es-rES/strings.xml
- app/src/main/res/values-fr-rFR/strings.xml
- app/src/main/res/values-it-rIT/strings.xml
- app/src/main/res/values-kn-rIN/strings.xml
- app/src/main/res/values-nl-rNL/strings.xml
- app/src/main/res/values-ru-rRU/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
I'm not sure if this is the best way to fix #280 but it is way better than showing individual toasts in my opinion.
> Improve method to notify users on copy

- app/src/main/java/com/beemdevelopment/aegis/importers/DatabaseImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/GoogleAuthUriImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/WinAuthImporter.java
This is the "standard" format discussed in #138.
> Add support for importing a plain text Google Authenticator URI file

- app/src/main/java/com/beemdevelopment/aegis/otp/GoogleAuthInfo.java
> Add support for otpauth://steam URI's

- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
> Fix bug where multiselect triggers copy animation

- app/src/main/java/com/beemdevelopment/aegis/Preferences.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryHolder.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
As discussed in Issue #373 I implemented the changes.
Got help from @LukasWillin, thanks!
> Option to change code display format (Issue #373)

- app/src/main/java/com/beemdevelopment/aegis/ui/AuthActivity.java
> Allow password reminder popup dismissal by typing

- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultBackupManager.java
> Append a timestamp to the filename of exported vaults

- app/build.gradle
- app/proguard-rules.pro
- app/src/main/java/com/beemdevelopment/aegis/importers/AuthenticatorPlusImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/SqlImporterHelper.java
> Import from ZIP for the Authenticator Plus, instead of SQLite databases

- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
> Fix an issue where backups where enabled when exporting the vault

- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
Also addresses other potential issues with the same cause. Fixes #363.
> Don't add new entries to the view if restoring from instance state

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/beemdevelopment/aegis/otp/GoogleAuthInfo.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/TransferEntriesActivity.java
- app/src/main/res/drawable/ic_qr_code_full.xml
- app/src/main/res/layout/activity_share_entry.xml
- app/src/main/res/menu/menu_action_mode.xml
- app/src/main/res/values/strings.xml
This PR adds the ability to transfer selected tokens to another device or app by generating QR codes.
Closes #424.
> Add ability to transfer tokens with qr codes

- app/src/main/java/com/beemdevelopment/aegis/Preferences.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
> Add an option to copy tokens on tap (and disable it by default)

- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
> Don't allow drag and drop if the entry list is filtered in any way

- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
Sometimes I get so enthusiastic when refactoring that I accidentally remove too much. This issue was introduced in 98a38b03e4bddc9d7c9a0d0c24ecb408950dbad0.
> Fix an issue where codes were not refreshed

- app/src/main/res/menu/menu_action_mode.xml
- app/src/main/res/values/strings.xml
Minor PR to fix the title for 'transfer' as reported in #471.
Fixes #471.
> Fix menu item title for transfer

- app/build.gradle
- app/src/main/java/com/beemdevelopment/aegis/helpers/PasswordStrengthHelper.java
- app/src/main/java/com/beemdevelopment/aegis/ui/Dialogs.java
- app/src/main/java/com/beemdevelopment/aegis/ui/slides/SecuritySetupSlide.java
- app/src/main/res/layout/dialog_password.xml
- app/src/main/res/layout/fragment_security_setup_slide.xml
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/strings.xml
I tinkered around with implementing a password strength meter as mentioned in #421.
There are a few things to do:
> Add password strength meter

- app/src/main/res/layout/activity_edit_entry.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/card_entry.xml
- app/src/main/res/layout/card_entry_compact.xml
- app/src/main/res/layout/card_entry_small.xml
- app/src/main/res/values-ldrtl/styles.xml
- app/src/main/res/values/styles.xml
This addresses most of the issues reported in #418. The intro is still broken, however.
It's not perfect, but a lot better than it used to be.
> Improve RTL support

- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultManager.java
I managed to clobber the filename of exports with fec2f3ff94dc3375b6fde325a8534dc079bb9b7d.
Fixes #495.
> Fix export filename (again)

- app/src/main/java/com/beemdevelopment/aegis/ui/views/TotpProgressBar.java
- app/src/main/res/layout/card_entry_compact.xml
- app/src/main/res/layout/card_entry_small.xml
> Fix division by zero when calculating progress for large periods

- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
Apparently onResume of MainActivity is sometimes called even if it's not the top level activity, causing IntroActivity or AuthActivity to be launched twice. This patch (uglily) prevents that from happening.
> Guard against starting multiple instances of IntroActivity or AuthActivity

- app/src/main/java/com/beemdevelopment/aegis/ThemeMap.java
- app/src/main/java/com/beemdevelopment/aegis/ui/AboutActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/AegisActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/AuthActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/ScannerActivity.java
- app/src/main/res/layout/activity_auth.xml
- app/src/main/res/values/styles.xml
- Neatly map configured themes to styles
- Make the dark NoActionBar themes inherit from Dark/AMOLED
> Fix two minor issues in themes

- app/src/main/java/com/beemdevelopment/aegis/ui/EditEntryActivity.java
> Combine ACTION_PICK and ACTION_GET_CONTENT when selecting an icon

- app/src/main/java/com/beemdevelopment/aegis/ui/Dialogs.java
- app/src/main/res/layout/dialog_password.xml
- app/src/main/res/layout/dialog_text_input.xml
> Automatically focus the EditText when showing text/password dialogs

- app/src/main/java/com/beemdevelopment/aegis/ui/AegisActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/AuthActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- Properly use 'inhibitBioPrompt'
- Don't show the biometric prompt when a password reminder is needed
> Fix behavior of AuthActivity under certain conditions

- app/src/main/java/com/beemdevelopment/aegis/importers/AuthyImporter.java
- app/src/main/java/com/beemdevelopment/aegis/util/JsonUtils.java
> Support importing proprietary tokens from Authy

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/GroupAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/GroupHolder.java
- app/src/main/res/layout/card_group.xml
- app/src/main/res/layout/card_slot.xml
- app/src/main/res/menu/menu_action_mode.xml
- app/src/main/res/menu/menu_scanner.xml
- app/src/main/res/values/strings.xml
I'm pretty sure I got all of them, but it's possible the linter missed some.
Fixes #92.
> Make all remaining hardcoded strings translatable

- app/src/main/res/values-v27/styles.xml
- app/src/main/res/values/styles.xml
Not very pretty, but I don't know of a better way.
Fixes #531.
> Set the correct navigation bar color pre API 27

- app/build.gradle
- app/src/androidTest/java/com/beemdevelopment/aegis/AegisTest.java
- app/src/androidTest/java/com/beemdevelopment/aegis/IntroTest.java
- app/src/androidTest/java/com/beemdevelopment/aegis/OverallTest.java
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/beemdevelopment/aegis/ui/AegisActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/IntroActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/intro/IntroActivityInterface.java
- app/src/main/java/com/beemdevelopment/aegis/ui/intro/IntroBaseActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/intro/SlideFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/intro/SlideIndicator.java
- app/src/main/java/com/beemdevelopment/aegis/ui/slides/DoneSlide.java
- app/src/main/java/com/beemdevelopment/aegis/ui/slides/SecurityPickerSlide.java
- app/src/main/java/com/beemdevelopment/aegis/ui/slides/SecuritySetupSlide.java
- app/src/main/java/com/beemdevelopment/aegis/ui/slides/WelcomeSlide.java
- app/src/main/res/drawable/circular_button_background.xml
- app/src/main/res/drawable/circular_button_done.xml
- app/src/main/res/drawable/circular_button_next.xml
- app/src/main/res/drawable/circular_button_prev.xml
- app/src/main/res/drawable/ic_arrow_left_black_24dp.xml
- app/src/main/res/drawable/ic_arrow_right_black_24dp.xml
- app/src/main/res/layout/activity_intro.xml
- app/src/main/res/layout/fragment_done_slide.xml
- app/src/main/res/layout/fragment_security_picker_slide.xml
- app/src/main/res/layout/fragment_security_setup_slide.xml
- app/src/main/res/layout/fragment_welcome_slide.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/styles.xml
This removes the dependency on AppIntro and replaces it with our own custom intro implementation, backed by ViewPager2. We're doing this because we want a more reliable and customizable onboarding for Aegis.
I've kept the design mostly the same as it was before, but tried to achieve a bit of a cleaner look:
src="https://alexbakker.me/u/efqid2ixly.png" width="200"> <img
src="https://alexbakker.me/u/oehmjm0rn9.png" width="200">
The intro currently looks broken in dark mode, but that will magically fix itself once #519 has been merged.
Closes #528, closes #514, closes #418, closes #349 and closes #227.
> Replace AppIntro with a new custom intro

- app/src/main/java/com/beemdevelopment/aegis/ui/Dialogs.java
- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/ScannerActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/SelectEntriesActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/TransferEntriesActivity.java
- app/src/main/res/layout/activity_share_entry.xml
- app/src/main/res/values-ar-rSA/strings.xml
- app/src/main/res/values-cs-rCZ/strings.xml
- app/src/main/res/values-de-rDE/strings.xml
- app/src/main/res/values-el-rGR/strings.xml
- app/src/main/res/values-es-rES/strings.xml
- app/src/main/res/values-fi-rFI/strings.xml
- app/src/main/res/values-fr-rFR/strings.xml
- app/src/main/res/values-hu-rHU/strings.xml
- app/src/main/res/values-it-rIT/strings.xml
- app/src/main/res/values-kn-rIN/strings.xml
- app/src/main/res/values-nl-rNL/strings.xml
- app/src/main/res/values-pl-rPL/strings.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values-pt-rPT/strings.xml
- app/src/main/res/values-ru-rRU/strings.xml
- app/src/main/res/values-tr-rTR/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
> Replace some string definitions with plurals definitions

- app/src/main/java/com/beemdevelopment/aegis/helpers/SimpleItemTouchHelperCallback.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryHolder.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
- app/src/main/res/drawable/ic_baseline_menu_black_32.xml
- app/src/main/res/layout/card_entry.xml
- app/src/main/res/layout/card_entry_compact.xml
- app/src/main/res/layout/card_entry_small.xml
Fixes #492 
List of changes:
1. Allows user to start dragging immediately after long pressing an entry
2. Improve user discoverability by displaying drag handle when only 1 entry is selected
3. Fixes the issue where dragging is still disabled when deselecting all but 1 entry, if that entry is not the first entry selected
Please let me know if there are any issues or improvements to be made.
> Improve usability of drag-and-drop feature

- app/src/main/java/com/beemdevelopment/aegis/helpers/FabScrollHelper.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
Added listener to the MainActivity for whenever the list changes. MainActivity now resets the visibility of the FAB when triggered.
Closes #128
> Fix hidden FAB when list changes

- app/src/main/java/com/beemdevelopment/aegis/helpers/EditTextHelper.java
- app/src/main/java/com/beemdevelopment/aegis/otp/GoogleAuthInfo.java
- app/src/main/java/com/beemdevelopment/aegis/ui/EditEntryActivity.java
> Strip " " and "-" when parsing secrets

- app/src/main/java/com/beemdevelopment/aegis/importers/DatabaseImporter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/Dialogs.java
- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
- app/src/main/res/layout/card_importer.xml
- app/src/main/res/layout/dialog_importers.xml
- app/src/main/res/values/strings.xml
> Display some help text in the importer selection dialog

- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
Also, only scan for QR codes, not all bar codes that ZXing supports.
> Combine ACTION_PICK and ACTION_GET_CONTENT when selecting an image to scan

- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
> After adding a new entry, scroll to it and highlight it

- app/src/main/java/com/beemdevelopment/aegis/importers/GoogleAuthImporter.java
See: https://github.com/beemdevelopment/Aegis/issues/593#issuecomment-751346120
> Use GoogleAuthInfo.parseSecret for secrets from Google Authenticator

- app/src/main/java/com/beemdevelopment/aegis/AegisApplication.java
- app/src/main/java/com/beemdevelopment/aegis/ui/AegisActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
Really not a fan of this fix, but I'm afraid we have no other option other than removing the "auto lock on minimize" option entirely.
> Fix an issue where the app would lock when showing DocumentsUI

- app/src/main/java/com/beemdevelopment/aegis/importers/AuthyImporter.java
> Don't rely on accountType to detect proprietary Authy tokens

- app/src/main/java/com/beemdevelopment/aegis/ui/AegisActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesFragment.java
- app/src/main/res/values/strings.xml
> Simplify the auto lock block logic and show an error if DocumentsUI is missing

- app/src/main/AndroidManifest.xml
> Explicitly opt out of WebView usage statistics collection

- app/build.gradle
- app/src/main/java/com/beemdevelopment/aegis/helpers/FabScrollHelper.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/SelectEntriesActivity.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/activity_select_entries.xml
- app/src/main/res/layout/dialog_add_entry.xml
- app/src/main/res/values-ldrtl/styles.xml
- app/src/main/res/values/styles.xml
This also removes the dependency on ``com.getbase:floatingactionbutton``.
> Replace the FAB with a bottom sheet dialog

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
> Add support for creating entries from shared images

- app/src/main/java/com/beemdevelopment/aegis/ui/EditEntryActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/dialogs/Dialogs.java
Fixes #758
Not sure if I should create a new string instead of using `unknown_issuer`, since it is not intended to be used mid-sentence.
> Fix blank text in delete dialog for entries with no issuer

- app/src/main/java/com/beemdevelopment/aegis/icons/IconPack.java
Check if the icon issuers contain the token issuer or vice versa.
Fixes #761
> Improve icon suggestions

- app/src/main/java/com/beemdevelopment/aegis/ui/EditEntryActivity.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultEntry.java
- app/src/main/res/drawable/ic_baseline_notes_black_24.xml
- app/src/main/res/layout/activity_edit_entry.xml
- app/src/main/res/values/strings.xml
Reference #782 
@alexbakker I've added the note field as a string to the EditEntryActivity. It exports when the JSON option is selected.
I was wondering - maybe an info icon on the far right of the entry item could be useful. It would be shown if a note was added, and if clicked would show a popup or toast with the note. This icon could then be hid when long-pressed. Opinion?
> add note text field when editing entry

- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
- app/src/main/res/layout/chip_material.xml
- app/src/main/res/layout/dialog_select_groups.xml
> Changed the Chip to match the background in Amoled and Dark Mode

- app/src/main/java/com/beemdevelopment/aegis/Preferences.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences_behavior.xml
> Added Focus Search on App Start

- app/src/main/java/com/beemdevelopment/aegis/ui/dialogs/Dialogs.java
- app/src/main/res/layout/dialog_delete_entry.xml
- app/src/main/res/values-bg-rBG/strings.xml
- app/src/main/res/values-cs-rCZ/strings.xml
- app/src/main/res/values-da-rDK/strings.xml
- app/src/main/res/values-de-rDE/strings.xml
- app/src/main/res/values-el-rGR/strings.xml
- app/src/main/res/values-es-rES/strings.xml
- app/src/main/res/values-eu-rES/strings.xml
- app/src/main/res/values-fr-rFR/strings.xml
- app/src/main/res/values-in-rID/strings.xml
- app/src/main/res/values-it-rIT/strings.xml
- app/src/main/res/values-ja-rJP/strings.xml
- app/src/main/res/values-lt-rLT/strings.xml
- app/src/main/res/values-lv-rLV/strings.xml
- app/src/main/res/values-nl-rNL/strings.xml
- app/src/main/res/values-pl-rPL/strings.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values-ro-rRO/strings.xml
- app/src/main/res/values-ru-rRU/strings.xml
- app/src/main/res/values-tr-rTR/strings.xml
- app/src/main/res/values-uk-rUA/strings.xml
- app/src/main/res/values-vi-rVN/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
Issue : #792
PR continution : #815 
Updated Strings to get the correct dialog
I am sorry for making a mess in this repo by making double PR for 2 times
> Updated Delete Dialog

- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
Fix #874 
Automated tests passed and I'm not getting problems through manual testing
> Don't hide "Add entry" button when a DPad key is pressed

- app/build.gradle
- app/src/main/java/com/beemdevelopment/aegis/importers/BitwardenImporter.java
- app/src/main/java/com/beemdevelopment/aegis/importers/DatabaseImporter.java
- app/src/main/res/raw/notices.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/com/beemdevelopment/aegis/importers/DatabaseImporterTest.java
- app/src/test/resources/com/beemdevelopment/aegis/importers/bitwarden.csv
- app/src/test/resources/com/beemdevelopment/aegis/importers/bitwarden.json
> Add Bitwarden importer

- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
> Restore search query on screen rotation

- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
Fix #907
This should be pretty straightforward, let me know if a dedicated function or something like that is preferred
> Sort list after editing entry

- app/src/main/java/com/beemdevelopment/aegis/importers/GoogleAuthImporter.java
- app/src/main/res/values/strings.xml
Fix #918 
I'm unsure about this tho. I tested it with two Google Authenticator versions, but is it possible that unencrypted entries exist in the new version?
> Check if Google Authenticator entries are encrypted

- app/build.gradle
- app/src/androidTest/java/com/beemdevelopment/aegis/AegisTest.java
- app/src/androidTest/java/com/beemdevelopment/aegis/BackupExportTest.java
- app/src/androidTest/java/com/beemdevelopment/aegis/DeepLinkTest.java
- app/src/androidTest/java/com/beemdevelopment/aegis/PanicTriggerTest.java
- app/src/androidTest/java/com/beemdevelopment/aegis/vault/VaultRepositoryTest.java
- app/src/androidTest/java/com/beemdevelopment/aegis/vectors/VaultEntries.java
- app/src/main/java/com/beemdevelopment/aegis/AegisBackupAgent.java
- app/src/main/java/com/beemdevelopment/aegis/ui/dialogs/Dialogs.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/ImportExportPreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/SecurityPreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultFile.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultFileCredentials.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultManager.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultRepository.java
- app/src/main/java/com/beemdevelopment/aegis/vault/slots/PasswordSlot.java
- app/src/main/java/com/beemdevelopment/aegis/vault/slots/Slot.java
- app/src/main/java/com/beemdevelopment/aegis/vault/slots/SlotList.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences_security.xml
- app/src/test/java/com/beemdevelopment/aegis/importers/DatabaseImporterTest.java
- app/src/test/java/com/beemdevelopment/aegis/vault/slots/SlotTest.java
- app/src/test/java/com/beemdevelopment/aegis/vectors/VaultEntries.java
> Add an option to set a separate password for backups and exports

- app/src/androidTest/java/com/beemdevelopment/aegis/OverallTest.java
- app/src/main/java/com/beemdevelopment/aegis/crypto/otp/MOTP.java
- app/src/main/java/com/beemdevelopment/aegis/otp/GoogleAuthInfo.java
- app/src/main/java/com/beemdevelopment/aegis/otp/MotpInfo.java
- app/src/main/java/com/beemdevelopment/aegis/otp/OtpInfo.java
- app/src/main/java/com/beemdevelopment/aegis/ui/EditEntryActivity.java
- app/src/main/res/layout/activity_edit_entry.xml
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/com/beemdevelopment/aegis/crypto/otp/MOTPTest.java
- app/src/test/java/com/beemdevelopment/aegis/otp/MotpInfoTest.java
#608 Adds support for mOTP codes
I saw that this proposal had been accepted but no development had happened so I made this implementation. I am also happy to work on it further if changes are required :)
> Add MOTP support

- app/src/main/java/com/beemdevelopment/aegis/Preferences.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/ImportExportPreferencesFragment.java
- app/src/main/res/layout/dialog_plaintext_warning_options.xml
- app/src/main/res/values/strings.xml
#132 Since in the original discussion mentioned this option would be okay by default, I implemented it that way, but added an option to have it not show again
> Add warning banner after plaintext export

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/res/values/strings.xml
#729 parses shared text as a OTP and shows an appropriate error message on failure.
> Enable sharing text to Aegis

- app/src/androidTest/java/com/beemdevelopment/aegis/AegisTest.java
- app/src/androidTest/java/com/beemdevelopment/aegis/IntroTest.java
- app/src/androidTest/resources/com/beemdevelopment/aegis/aegis_encrypted.json
- app/src/androidTest/resources/com/beemdevelopment/aegis/aegis_plain.json
- app/src/main/java/com/beemdevelopment/aegis/importers/AegisImporter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/IntroActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/intro/IntroBaseActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/slides/WelcomeSlide.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultManager.java
- app/src/main/res/layout/fragment_welcome_slide.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
> Add an import button to the intro

- app/src/main/res/layout/activity_auth.xml
- app/src/main/res/values-w600dp/dimens.xml
- app/src/main/res/values-w60dp/dimens.xml
- app/src/main/res/values/dimens.xml
Proposed method of dealing with small screens; see #794
> Text is cutoff because of small display

- app/src/main/java/com/beemdevelopment/aegis/Preferences.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences_behavior.xml
> Minimize or Close app after copying OTP #805

- app/src/main/java/com/beemdevelopment/aegis/helpers/SimpleItemTouchHelperCallback.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
- app/src/main/res/layout/card_footer.xml
- app/src/main/res/values/strings.xml
> Add entries showing count

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/beemdevelopment/aegis/helpers/SafHelper.java
- app/src/main/java/com/beemdevelopment/aegis/helpers/SimpleTextWatcher.java
- app/src/main/java/com/beemdevelopment/aegis/ui/AboutActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/AuthActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/EditEntryActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/GroupManagerActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/ImportEntriesActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/TransferEntriesActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/AppearancePreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/intro/IntroBaseActivity.java
- app/src/main/res/menu/menu_groups.xml
WIP, but submitting this as a draft now in case anyone else was planning on working on this.
> Add support for predictive back gesture

- app/src/androidTest/java/com/beemdevelopment/aegis/OverallTest.java
- app/src/main/java/com/beemdevelopment/aegis/Preferences.java
- app/src/main/java/com/beemdevelopment/aegis/helpers/SimpleItemTouchHelperCallback.java
- app/src/main/java/com/beemdevelopment/aegis/helpers/comparators/FavoriteComparator.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryHolder.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultEntry.java
- app/src/main/res/drawable-anydpi/ic_set_favorite.xml
- app/src/main/res/drawable-anydpi/ic_unset_favorite.xml
- app/src/main/res/layout/card_entry.xml
- app/src/main/res/layout/card_entry_compact.xml
- app/src/main/res/layout/card_entry_small.xml
- app/src/main/res/menu/menu_action_mode.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
This pull request adds the ability to pin entries by long pressing the desired entries. A favorite/star icon will be shown in the action bar which allows the user to toggle between the favorite state. Favorited entries will always be shown on top with a yellow bar in front of them to distinguish them from the others.
Closes #983.
> Add ability to pin/favorite entries

- app/src/main/java/com/beemdevelopment/aegis/Preferences.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/AppearancePreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryHolder.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences_appearance.xml
#662 
I implemented this so that it is slightly more compact than the normal view in addition to removing the icons because I think it looks better. Let me know what you think.
<p float="left">
</p>
> Add 'No Icons' view mode

- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/ImportExportPreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/vault/Vault.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultRepository.java
- app/src/main/res/layout/dialog_export.xml
- app/src/main/res/values/strings.xml
> Allow exporting specific groups

- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryHolder.java
> Only copy code if not hidden

- app/src/main/java/com/beemdevelopment/aegis/ui/TransferEntriesActivity.java
- app/src/main/res/layout/activity_share_entry.xml
- app/src/main/res/layout/fragment_welcome_slide.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
Co-authored-by: orange-elephant <88595467+orange-elephant@users.noreply.github.com>
Closes #1034
> Copy URI to clipboard when using transfer entries

- app/src/androidTest/java/com/beemdevelopment/aegis/BackupExportTest.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/ImportExportPreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/PreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultRepository.java
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/strings.xml
Closes #954
I'm marking this as a draft because I'd like to ask if there's a preferred layout or style for the output. This is what I'm getting (zoom decreased to 50%), but it's pretty easy to adjust:
I'm going to create the test unit when I have more time to focus, I'm going to add more fields for now
Edit: would a table structure be better?
> Export vault to HTML

- app/src/main/java/com/beemdevelopment/aegis/ui/components/DropdownCheckBoxes.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/ImportExportPreferencesFragment.java
- app/src/main/res/layout/dialog_export.xml
- app/src/main/res/layout/dropdown_checkbox.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/strings.xml
As the groundwork for adding to multiple groups and to improve the existing multi-group selection in exports
<p float="left">
</p>
> Create checkboxes dropdown component

- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/ImportExportPreferencesFragment.java
With the new options to export specific groups, users could attempt to export 0 groups, which would show an error toast and force them to start over again.
This PR matches the behaviour of accepting the unencrypted risk by disabling the positive and neutral buttons if the selected options don't result in a valid state for exporting, and uses an error message on the groups selection layout instead of a toast message after failing.
<p float="left">
</p>
> Only enable export buttons if options are in a valid state

- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
This pull request fixes the bug where the user was prompted with a "No entries" view after deleting the last entry from the search results.
Fixes #1099.
> Fix empty state while using search filter

- app/src/main/java/com/beemdevelopment/aegis/ui/AboutActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/AssignIconsActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/EditEntryActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/GroupManagerActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/ImportEntriesActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/TransferEntriesActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/slides/SecurityPickerSlide.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
- gradle.properties
Future versions of AGP will force us to do this, so we might as well get it over with now.
> Transition to non-final resource IDs and non-transitive R classes

- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
- app/src/main/res/menu/menu_action_mode.xml
- app/src/main/res/values/strings.xml
This pull requests adds a menu item to select all tokens at once after the user selected a token.
Closes #1199
> Add ability to select all tokens

- app/src/main/java/com/beemdevelopment/aegis/SortCategory.java
This pull requests adds an additional comparator to improve the issuer and account sorting methods for our list view as suggested in #1229.
Closes #1229
> Improve issuer and account sorting

- app/src/main/java/com/beemdevelopment/aegis/importers/AuthyImporter.java
The issue was introduced in: 69f0bb4fbcf98aa0f5ec254fe5dda513527e0063.
Fixes #1077.
> Pass down the root shell to every SuFile for the Authy importer

- README.md
Hi!
I've added the delta-aegis-icons icon pack for the lovers of matte/pastel icons, mantained by me.
It's simply the aegis-icons pack but with Delta's colors nothing too fancy, but if someone want to contribute the're free to do so.
The showcase file is inside our repository.
Hope this is okay, love the project!
> Add delta-aegis-icons to the Readme

- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
- app/src/main/res/layout/card_entry_compact.xml
- app/src/main/res/layout/card_entry_small.xml
> Fix shape of favorited entries

- app/src/main/res/layout/activity_auth.xml
My smallest PR to date...
but this was bugging me
> Fix padding unlock button

- app/src/main/java/com/beemdevelopment/aegis/ui/glide/GlideHelper.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/AssignIconHolder.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/IconHolder.java
Loading drawables using Glide while the size of the ImageView is not known yet appears to result in a blurry mess.
> Don't use Glide to load drawable resources

- app/src/main/java/com/beemdevelopment/aegis/ui/GroupManagerActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/dialogs/Dialogs.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/GroupAdapter.java
- app/src/main/java/com/beemdevelopment/aegis/ui/views/GroupHolder.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultRepository.java
- app/src/main/res/layout/card_group.xml
- app/src/main/res/values/strings.xml
This is one of the most requested feature mentioned in #27
> Renaming of Groups

- app/src/main/java/com/beemdevelopment/aegis/ui/AssignIconsActivity.java
> Fix icon pack selector in AssignIconsActivity

- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
Fixes #762 
Group would remain selected through rotation
https://github.com/beemdevelopment/Aegis/assets/11408319/60a5cf88-dc8e-4ebf-90e0-8cca8363a697
> Remember group selection after screen rotate

- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryHolder.java
> Fix Spacing Issue With Name

- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/vault/Vault.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultRepository.java
> Save the vault when saving group filter right after a vault version bump

- app/src/main/res/layout/activity_edit_entry.xml
> Make EditEntryActivity scrollable again

- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
This is a workaround for #1342.
> Start auth/intro activities from onStart to work around an Android bug

- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
> Hide keyboard on scroll when search field is focused

- app/src/main/java/com/beemdevelopment/aegis/ui/views/AuditLogHolder.java
- app/src/main/res/values-ar-rSA/strings.xml
- app/src/main/res/values-bg-rBG/strings.xml
- app/src/main/res/values-ca-rES/strings.xml
- app/src/main/res/values-cs-rCZ/strings.xml
- app/src/main/res/values-da-rDK/strings.xml
- app/src/main/res/values-de-rDE/strings.xml
- app/src/main/res/values-el-rGR/strings.xml
- app/src/main/res/values-es-rES/strings.xml
- app/src/main/res/values-fi-rFI/strings.xml
- app/src/main/res/values-fr-rFR/strings.xml
- app/src/main/res/values-fy-rNL/strings.xml
- app/src/main/res/values-hu-rHU/strings.xml
- app/src/main/res/values-lv-rLV/strings.xml
- app/src/main/res/values-nl-rNL/strings.xml
- app/src/main/res/values-pl-rPL/strings.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values-ro-rRO/strings.xml
- app/src/main/res/values-ru-rRU/strings.xml
- app/src/main/res/values-sk-rSK/strings.xml
- app/src/main/res/values-vi-rVN/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
> Fix datetime parsing in Audit Log

- app/src/main/java/com/beemdevelopment/aegis/Preferences.java
- app/src/main/java/com/beemdevelopment/aegis/ui/dialogs/Dialogs.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/BackupsPreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultBackupManager.java
- app/src/main/res/values/strings.xml
> Infinite backups

- app/src/main/java/com/beemdevelopment/aegis/vault/slots/SlotList.java
- app/src/test/java/com/beemdevelopment/aegis/vault/slots/SlotTest.java
> Strip a biometric slot when a backup is made

- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/PreferencesActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/AppearancePreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/BackupsPreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/BehaviorPreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/ImportExportPreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/MainPreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/PreferencesFragment.java
- app/src/main/java/com/beemdevelopment/aegis/ui/fragments/preferences/SecurityPreferencesFragment.java
> Remove preferences result

- app/src/main/res/layout/dialog_export.xml
Reported by @valentinb102 on Matrix.
> Make the export dialog scrollable

- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
> Trim spaces from the search filter

- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
> Prevent copying when revealing code

- app/src/main/proto/google_auth.proto
> Fix batch_index in Google Authenticator export

- app/src/main/res/layout/activity_edit_entry.xml
After reading #1508 I thought it would make more sense to make the secret in the EditEntryActivity multiline to improve the UX a bit. Might be unrelated to the issue.
> Make secret multiline

- app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryHolder.java
Before, the dots may turn red if the animation duration scale is set to 0.
> Always cancel the delayed color change when hiding the code

- app/build.gradle
- app/src/main/java/com/beemdevelopment/aegis/ThemeMap.java
- app/src/main/java/com/beemdevelopment/aegis/ui/AegisActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/ScannerActivity.java
- app/src/main/res/layout/activity_about.xml
- app/src/main/res/layout/activity_assign_icons.xml
- app/src/main/res/layout/activity_auth.xml
- app/src/main/res/layout/activity_edit_entry.xml
- app/src/main/res/layout/activity_groups.xml
- app/src/main/res/layout/activity_import_entries.xml
- app/src/main/res/layout/activity_preferences.xml
- app/src/main/res/layout/activity_scanner.xml
- app/src/main/res/layout/activity_share_entry.xml
- app/src/main/res/raw/aboutlibraries.json
- app/src/main/res/values/themes.xml
- app/src/test/java/com/beemdevelopment/aegis/PreferencesTest.java
- app/src/test/java/com/beemdevelopment/aegis/helpers/QrCodeAnalyzerTest.java
- app/src/test/java/com/beemdevelopment/aegis/importers/DatabaseImporterTest.java
- app/src/test/java/com/beemdevelopment/aegis/otp/GoogleAuthInfoTest.java
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
This also includes changes to make the status guard hack work on Android 15 and a couple of small adjustments to support edge-to-edge in all activities.
> Bump targetSdkVersion to 35 and update dependencies

- app/src/main/res/layout/card_entry_tile.xml
> Fix layout height in tiles mode

- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
> Reset selection state when changing groups

- app/src/main/java/com/beemdevelopment/aegis/importers/TwoFASImporter.java
> Store service name as issuer and tolerate spaces in secret for 2FAS

- app/src/main/java/com/beemdevelopment/aegis/helpers/BitmapHelper.java
- app/src/main/java/com/beemdevelopment/aegis/ui/EditEntryActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/ImportEntriesActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/MainActivity.java
- app/src/main/java/com/beemdevelopment/aegis/ui/tasks/IconOptimizationTask.java
- app/src/main/java/com/beemdevelopment/aegis/vault/Vault.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultEntry.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultEntryIcon.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultEntryIconException.java
- app/src/main/java/com/beemdevelopment/aegis/vault/VaultRepository.java
- app/src/main/res/values/strings.xml
> Store non-SVG icons at a maximum of 512x512 and migrate existing icons

- app/src/main/java/com/beemdevelopment/aegis/ui/TransferEntriesActivity.java
- app/src/main/res/layout/activity_share_entry.xml
- app/src/main/res/values/strings.xml
> Add brightness slider for transfer activity

- app/src/main/res/values/arrays.xml
> Specify country code for the Portuguese translation
